#ifndef TCLOCK_COLOR_H
#define TCLOCL_COLOR_H

#ifndef WM_DWMCOLORIZATIONCOLORCHANGED
#	define WM_DWMCOLORIZATIONCOLORCHANGED 0x0320
#endif // WM_DWMCOLORIZATIONCOLORCHANGED

#define TCOLOR_MASK		0xFFFFFFC0
#define TCOLOR_MAGIC	0xFAFCFEC0
#define TCOLOR(tcolor) (TCOLOR_MAGIC|tcolor)
enum{
	TCOLOR_BEGIN_		=50,
	TCOLOR_DEFAULT		=50,
	TCOLOR_TRANSPARENT,
	TCOLOR_THEME,
	TCOLOR_THEME2,
	TCOLOR_END_,
};

void OnTColor_DWMCOLORIZATIONCOLORCHANGED(unsigned argb);
unsigned GetTColor(unsigned agbr,int useraw); // returns ogbr
#endif // TCLOCK_COLOR_H
