#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC = 
CFLAGS = -std=c99 -Wall -D__MINGW_USE_VC2005_COMPAT -DWINVER=0x0501
RESINC = 
LIBDIR = 
LIB = -lAdvapi32 -luser32 -lgdi32 -lmsvcr100
LDFLAGS = 

INC_APP = $(INC)
CFLAGS_APP = $(CFLAGS) -O2 -DNDEBUG
RESINC_APP = $(RESINC)
RCFLAGS_APP = $(RCFLAGS)
LIBDIR_APP = $(LIBDIR) -LRelease\Win32
LIB_APP = $(LIB) -lPsapi -lole32 -lComdlg32 -lshlwapi -lVersion -lcomctl32 -lWinmm -lWs2_32 -lMpr -lUuid -ltClock
LDFLAGS_APP = $(LDFLAGS) -s
OBJDIR_APP = .obj
DEP_APP = 
OUT_APP = Release\\Win32\\Clock.exe

INC_DLL = $(INC)
CFLAGS_DLL = $(CFLAGS) -O2 -DNDEBUG
RESINC_DLL = $(RESINC)
RCFLAGS_DLL = $(RCFLAGS)
LIBDIR_DLL = $(LIBDIR)
LIB_DLL = $(LIB)
LDFLAGS_DLL = $(LDFLAGS) -s
OBJDIR_DLL = .obj
DEP_DLL = 
OUT_DLL = Release\\Win32\\tClock.dll

INC_APP_DEBUG = $(INC)
CFLAGS_APP_DEBUG = $(CFLAGS) -g
RESINC_APP_DEBUG = $(RESINC)
RCFLAGS_APP_DEBUG = $(RCFLAGS)
LIBDIR_APP_DEBUG = $(LIBDIR) -LDebug\Win32
LIB_APP_DEBUG = $(LIB) -lPsapi -lole32 -lComdlg32 -lshlwapi -lVersion -lcomctl32 -lWinmm -lWs2_32 -lMpr -lUuid -ltClock
LDFLAGS_APP_DEBUG = $(LDFLAGS)
OBJDIR_APP_DEBUG = .obj\\dbg
DEP_APP_DEBUG = 
OUT_APP_DEBUG = Debug\\Win32\\Clock.exe

INC_DLL_DEBUG = $(INC)
CFLAGS_DLL_DEBUG = $(CFLAGS) -g
RESINC_DLL_DEBUG = $(RESINC)
RCFLAGS_DLL_DEBUG = $(RCFLAGS)
LIBDIR_DLL_DEBUG = $(LIBDIR)
LIB_DLL_DEBUG = $(LIB)
LDFLAGS_DLL_DEBUG = $(LDFLAGS)
OBJDIR_DLL_DEBUG = .obj\\dbg
DEP_DLL_DEBUG = 
OUT_DLL_DEBUG = Debug\\Win32\\tClock.dll

OBJ_APP = $(OBJDIR_APP)\\Source\\Clock\\pageformat.o $(OBJDIR_APP)\\Source\\Clock\\propsheet.o $(OBJDIR_APP)\\Source\\Clock\\soundselect.o $(OBJDIR_APP)\\Source\\Clock\\tClock.o $(OBJDIR_APP)\\Source\\Clock\\timer.o $(OBJDIR_APP)\\Source\\Clock\\utl.o $(OBJDIR_APP)\\Source\\Clock\\BounceWind.o $(OBJDIR_APP)\\Source\\Clock\\ExitWindows.o $(OBJDIR_APP)\\Source\\Clock\\GetSetTimePerms.o $(OBJDIR_APP)\\Source\\Clock\\PageHotKey.o $(OBJDIR_APP)\\Source\\Clock\\PageMisc.o $(OBJDIR_APP)\\Source\\Clock\\PageMouse.o $(OBJDIR_APP)\\Source\\Clock\\PageQuicky.o $(OBJDIR_APP)\\Source\\Clock\\PageQuickyMenu.o $(OBJDIR_APP)\\Source\\Clock\\SNTP.o $(OBJDIR_APP)\\Source\\Clock\\StopWatch.o $(OBJDIR_APP)\\Source\\Clock\\alarm.o $(OBJDIR_APP)\\Source\\Clock\\alarmday.o $(OBJDIR_APP)\\Source\\Clock\\main.o $(OBJDIR_APP)\\Source\\Clock\\menu.o $(OBJDIR_APP)\\Source\\Clock\\mouse.o $(OBJDIR_APP)\\Source\\Clock\\pageabout.o $(OBJDIR_APP)\\Source\\Clock\\pagealarm.o $(OBJDIR_APP)\\Source\\Clock\\pagecolor.o

OBJ_DLL = $(OBJDIR_DLL)\\Source\\DLL\\Tclock.o $(OBJDIR_DLL)\\Source\\DLL\\font.o $(OBJDIR_DLL)\\Source\\DLL\\format.o $(OBJDIR_DLL)\\Source\\DLL\\main.o $(OBJDIR_DLL)\\Source\\DLL\\newapi.o $(OBJDIR_DLL)\\Source\\DLL\\utl.o $(OBJDIR_DLL)\\Source\\DLL\\version.o

OBJ_APP_DEBUG = $(OBJDIR_APP_DEBUG)\\Source\\Clock\\pageformat.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\propsheet.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\soundselect.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\tClock.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\timer.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\utl.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\BounceWind.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\ExitWindows.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\GetSetTimePerms.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\PageHotKey.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\PageMisc.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\PageMouse.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\PageQuicky.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\PageQuickyMenu.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\SNTP.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\StopWatch.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\alarm.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\alarmday.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\main.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\menu.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\mouse.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\pageabout.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\pagealarm.o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\pagecolor.o

OBJ_DLL_DEBUG = $(OBJDIR_DLL_DEBUG)\\Source\\DLL\\Tclock.o $(OBJDIR_DLL_DEBUG)\\Source\\DLL\\font.o $(OBJDIR_DLL_DEBUG)\\Source\\DLL\\format.o $(OBJDIR_DLL_DEBUG)\\Source\\DLL\\main.o $(OBJDIR_DLL_DEBUG)\\Source\\DLL\\newapi.o $(OBJDIR_DLL_DEBUG)\\Source\\DLL\\utl.o $(OBJDIR_DLL_DEBUG)\\Source\\DLL\\version.o

all: dll app dll_debug app_debug

clean: clean_app clean_dll clean_app_debug clean_dll_debug

before_app: 
	cmd /c if not exist Release\\Win32 md Release\\Win32
	cmd /c if not exist $(OBJDIR_APP)\\Source\\Clock md $(OBJDIR_APP)\\Source\\Clock

after_app: 

app: before_app out_app after_app

out_app: before_app $(OBJ_APP) $(DEP_APP)
	$(LD) $(LIBDIR_APP) -o $(OUT_APP) $(OBJ_APP)  $(LDFLAGS_APP) -mwindows $(LIB_APP)

$(OBJDIR_APP)\\Source\\Clock\\pageformat.o: Source\\Clock\\pageformat.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\pageformat.c -o $(OBJDIR_APP)\\Source\\Clock\\pageformat.o

$(OBJDIR_APP)\\Source\\Clock\\propsheet.o: Source\\Clock\\propsheet.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\propsheet.c -o $(OBJDIR_APP)\\Source\\Clock\\propsheet.o

$(OBJDIR_APP)\\Source\\Clock\\soundselect.o: Source\\Clock\\soundselect.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\soundselect.c -o $(OBJDIR_APP)\\Source\\Clock\\soundselect.o

$(OBJDIR_APP)\\Source\\Clock\\tClock.o: Source\\Clock\\tClock.rc
	$(WINDRES) -i Source\\Clock\\tClock.rc -J rc -o $(OBJDIR_APP)\\Source\\Clock\\tClock.o -O coff $(INC_APP)

$(OBJDIR_APP)\\Source\\Clock\\timer.o: Source\\Clock\\timer.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\timer.c -o $(OBJDIR_APP)\\Source\\Clock\\timer.o

$(OBJDIR_APP)\\Source\\Clock\\utl.o: Source\\Clock\\utl.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\utl.c -o $(OBJDIR_APP)\\Source\\Clock\\utl.o

$(OBJDIR_APP)\\Source\\Clock\\BounceWind.o: Source\\Clock\\BounceWind.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\BounceWind.c -o $(OBJDIR_APP)\\Source\\Clock\\BounceWind.o

$(OBJDIR_APP)\\Source\\Clock\\ExitWindows.o: Source\\Clock\\ExitWindows.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\ExitWindows.c -o $(OBJDIR_APP)\\Source\\Clock\\ExitWindows.o

$(OBJDIR_APP)\\Source\\Clock\\GetSetTimePerms.o: Source\\Clock\\GetSetTimePerms.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\GetSetTimePerms.c -o $(OBJDIR_APP)\\Source\\Clock\\GetSetTimePerms.o

$(OBJDIR_APP)\\Source\\Clock\\PageHotKey.o: Source\\Clock\\PageHotKey.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\PageHotKey.c -o $(OBJDIR_APP)\\Source\\Clock\\PageHotKey.o

$(OBJDIR_APP)\\Source\\Clock\\PageMisc.o: Source\\Clock\\PageMisc.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\PageMisc.c -o $(OBJDIR_APP)\\Source\\Clock\\PageMisc.o

$(OBJDIR_APP)\\Source\\Clock\\PageMouse.o: Source\\Clock\\PageMouse.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\PageMouse.c -o $(OBJDIR_APP)\\Source\\Clock\\PageMouse.o

$(OBJDIR_APP)\\Source\\Clock\\PageQuicky.o: Source\\Clock\\PageQuicky.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\PageQuicky.c -o $(OBJDIR_APP)\\Source\\Clock\\PageQuicky.o

$(OBJDIR_APP)\\Source\\Clock\\PageQuickyMenu.o: Source\\Clock\\PageQuickyMenu.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\PageQuickyMenu.c -o $(OBJDIR_APP)\\Source\\Clock\\PageQuickyMenu.o

$(OBJDIR_APP)\\Source\\Clock\\SNTP.o: Source\\Clock\\SNTP.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\SNTP.c -o $(OBJDIR_APP)\\Source\\Clock\\SNTP.o

$(OBJDIR_APP)\\Source\\Clock\\StopWatch.o: Source\\Clock\\StopWatch.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\StopWatch.c -o $(OBJDIR_APP)\\Source\\Clock\\StopWatch.o

$(OBJDIR_APP)\\Source\\Clock\\alarm.o: Source\\Clock\\alarm.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\alarm.c -o $(OBJDIR_APP)\\Source\\Clock\\alarm.o

$(OBJDIR_APP)\\Source\\Clock\\alarmday.o: Source\\Clock\\alarmday.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\alarmday.c -o $(OBJDIR_APP)\\Source\\Clock\\alarmday.o

$(OBJDIR_APP)\\Source\\Clock\\main.o: Source\\Clock\\main.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\main.c -o $(OBJDIR_APP)\\Source\\Clock\\main.o

$(OBJDIR_APP)\\Source\\Clock\\menu.o: Source\\Clock\\menu.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\menu.c -o $(OBJDIR_APP)\\Source\\Clock\\menu.o

$(OBJDIR_APP)\\Source\\Clock\\mouse.o: Source\\Clock\\mouse.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\mouse.c -o $(OBJDIR_APP)\\Source\\Clock\\mouse.o

$(OBJDIR_APP)\\Source\\Clock\\pageabout.o: Source\\Clock\\pageabout.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\pageabout.c -o $(OBJDIR_APP)\\Source\\Clock\\pageabout.o

$(OBJDIR_APP)\\Source\\Clock\\pagealarm.o: Source\\Clock\\pagealarm.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\pagealarm.c -o $(OBJDIR_APP)\\Source\\Clock\\pagealarm.o

$(OBJDIR_APP)\\Source\\Clock\\pagecolor.o: Source\\Clock\\pagecolor.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c Source\\Clock\\pagecolor.c -o $(OBJDIR_APP)\\Source\\Clock\\pagecolor.o

clean_app: 
	cmd /c del /f $(OBJ_APP) $(OUT_APP)
	cmd /c rd Release\\Win32
	cmd /c rd $(OBJDIR_APP)\\Source\\Clock

before_dll: 
	cmd /c if not exist Release\\Win32 md Release\\Win32
	cmd /c if not exist $(OBJDIR_DLL)\\Source\\DLL md $(OBJDIR_DLL)\\Source\\DLL

after_dll: 

dll: before_dll out_dll after_dll

out_dll: before_dll $(OBJ_DLL) $(DEP_DLL)
	$(LD) -shared $(LIBDIR_DLL) $(OBJ_DLL)  -o $(OUT_DLL) $(LDFLAGS_DLL) $(LIB_DLL)

$(OBJDIR_DLL)\\Source\\DLL\\Tclock.o: Source\\DLL\\Tclock.c
	$(CC) $(CFLAGS_DLL) $(INC_DLL) -c Source\\DLL\\Tclock.c -o $(OBJDIR_DLL)\\Source\\DLL\\Tclock.o

$(OBJDIR_DLL)\\Source\\DLL\\font.o: Source\\DLL\\font.c
	$(CC) $(CFLAGS_DLL) $(INC_DLL) -c Source\\DLL\\font.c -o $(OBJDIR_DLL)\\Source\\DLL\\font.o

$(OBJDIR_DLL)\\Source\\DLL\\format.o: Source\\DLL\\format.c
	$(CC) $(CFLAGS_DLL) $(INC_DLL) -c Source\\DLL\\format.c -o $(OBJDIR_DLL)\\Source\\DLL\\format.o

$(OBJDIR_DLL)\\Source\\DLL\\main.o: Source\\DLL\\main.c
	$(CC) $(CFLAGS_DLL) $(INC_DLL) -c Source\\DLL\\main.c -o $(OBJDIR_DLL)\\Source\\DLL\\main.o

$(OBJDIR_DLL)\\Source\\DLL\\newapi.o: Source\\DLL\\newapi.c
	$(CC) $(CFLAGS_DLL) $(INC_DLL) -c Source\\DLL\\newapi.c -o $(OBJDIR_DLL)\\Source\\DLL\\newapi.o

$(OBJDIR_DLL)\\Source\\DLL\\utl.o: Source\\DLL\\utl.c
	$(CC) $(CFLAGS_DLL) $(INC_DLL) -c Source\\DLL\\utl.c -o $(OBJDIR_DLL)\\Source\\DLL\\utl.o

$(OBJDIR_DLL)\\Source\\DLL\\version.o: Source\\DLL\\version.rc
	$(WINDRES) -i Source\\DLL\\version.rc -J rc -o $(OBJDIR_DLL)\\Source\\DLL\\version.o -O coff $(INC_DLL)

clean_dll: 
	cmd /c del /f $(OBJ_DLL) $(OUT_DLL)
	cmd /c rd Release\\Win32
	cmd /c rd $(OBJDIR_DLL)\\Source\\DLL

before_app_debug: 
	cmd /c if not exist Debug\\Win32 md Debug\\Win32
	cmd /c if not exist $(OBJDIR_APP_DEBUG)\\Source\\Clock md $(OBJDIR_APP_DEBUG)\\Source\\Clock

after_app_debug: 

app_debug: before_app_debug out_app_debug after_app_debug

out_app_debug: before_app_debug $(OBJ_APP_DEBUG) $(DEP_APP_DEBUG)
	$(LD) $(LIBDIR_APP_DEBUG) -o $(OUT_APP_DEBUG) $(OBJ_APP_DEBUG)  $(LDFLAGS_APP_DEBUG) -mwindows $(LIB_APP_DEBUG)

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\pageformat.o: Source\\Clock\\pageformat.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\pageformat.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\pageformat.o

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\propsheet.o: Source\\Clock\\propsheet.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\propsheet.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\propsheet.o

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\soundselect.o: Source\\Clock\\soundselect.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\soundselect.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\soundselect.o

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\tClock.o: Source\\Clock\\tClock.rc
	$(WINDRES) -i Source\\Clock\\tClock.rc -J rc -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\tClock.o -O coff $(INC_APP_DEBUG)

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\timer.o: Source\\Clock\\timer.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\timer.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\timer.o

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\utl.o: Source\\Clock\\utl.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\utl.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\utl.o

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\BounceWind.o: Source\\Clock\\BounceWind.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\BounceWind.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\BounceWind.o

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\ExitWindows.o: Source\\Clock\\ExitWindows.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\ExitWindows.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\ExitWindows.o

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\GetSetTimePerms.o: Source\\Clock\\GetSetTimePerms.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\GetSetTimePerms.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\GetSetTimePerms.o

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\PageHotKey.o: Source\\Clock\\PageHotKey.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\PageHotKey.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\PageHotKey.o

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\PageMisc.o: Source\\Clock\\PageMisc.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\PageMisc.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\PageMisc.o

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\PageMouse.o: Source\\Clock\\PageMouse.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\PageMouse.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\PageMouse.o

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\PageQuicky.o: Source\\Clock\\PageQuicky.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\PageQuicky.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\PageQuicky.o

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\PageQuickyMenu.o: Source\\Clock\\PageQuickyMenu.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\PageQuickyMenu.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\PageQuickyMenu.o

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\SNTP.o: Source\\Clock\\SNTP.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\SNTP.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\SNTP.o

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\StopWatch.o: Source\\Clock\\StopWatch.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\StopWatch.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\StopWatch.o

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\alarm.o: Source\\Clock\\alarm.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\alarm.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\alarm.o

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\alarmday.o: Source\\Clock\\alarmday.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\alarmday.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\alarmday.o

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\main.o: Source\\Clock\\main.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\main.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\main.o

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\menu.o: Source\\Clock\\menu.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\menu.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\menu.o

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\mouse.o: Source\\Clock\\mouse.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\mouse.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\mouse.o

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\pageabout.o: Source\\Clock\\pageabout.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\pageabout.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\pageabout.o

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\pagealarm.o: Source\\Clock\\pagealarm.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\pagealarm.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\pagealarm.o

$(OBJDIR_APP_DEBUG)\\Source\\Clock\\pagecolor.o: Source\\Clock\\pagecolor.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c Source\\Clock\\pagecolor.c -o $(OBJDIR_APP_DEBUG)\\Source\\Clock\\pagecolor.o

clean_app_debug: 
	cmd /c del /f $(OBJ_APP_DEBUG) $(OUT_APP_DEBUG)
	cmd /c rd Debug\\Win32
	cmd /c rd $(OBJDIR_APP_DEBUG)\\Source\\Clock

before_dll_debug: 
	cmd /c if not exist Debug\\Win32 md Debug\\Win32
	cmd /c if not exist $(OBJDIR_DLL_DEBUG)\\Source\\DLL md $(OBJDIR_DLL_DEBUG)\\Source\\DLL

after_dll_debug: 

dll_debug: before_dll_debug out_dll_debug after_dll_debug

out_dll_debug: before_dll_debug $(OBJ_DLL_DEBUG) $(DEP_DLL_DEBUG)
	$(LD) -shared $(LIBDIR_DLL_DEBUG) $(OBJ_DLL_DEBUG)  -o $(OUT_DLL_DEBUG) $(LDFLAGS_DLL_DEBUG) $(LIB_DLL_DEBUG)

$(OBJDIR_DLL_DEBUG)\\Source\\DLL\\Tclock.o: Source\\DLL\\Tclock.c
	$(CC) $(CFLAGS_DLL_DEBUG) $(INC_DLL_DEBUG) -c Source\\DLL\\Tclock.c -o $(OBJDIR_DLL_DEBUG)\\Source\\DLL\\Tclock.o

$(OBJDIR_DLL_DEBUG)\\Source\\DLL\\font.o: Source\\DLL\\font.c
	$(CC) $(CFLAGS_DLL_DEBUG) $(INC_DLL_DEBUG) -c Source\\DLL\\font.c -o $(OBJDIR_DLL_DEBUG)\\Source\\DLL\\font.o

$(OBJDIR_DLL_DEBUG)\\Source\\DLL\\format.o: Source\\DLL\\format.c
	$(CC) $(CFLAGS_DLL_DEBUG) $(INC_DLL_DEBUG) -c Source\\DLL\\format.c -o $(OBJDIR_DLL_DEBUG)\\Source\\DLL\\format.o

$(OBJDIR_DLL_DEBUG)\\Source\\DLL\\main.o: Source\\DLL\\main.c
	$(CC) $(CFLAGS_DLL_DEBUG) $(INC_DLL_DEBUG) -c Source\\DLL\\main.c -o $(OBJDIR_DLL_DEBUG)\\Source\\DLL\\main.o

$(OBJDIR_DLL_DEBUG)\\Source\\DLL\\newapi.o: Source\\DLL\\newapi.c
	$(CC) $(CFLAGS_DLL_DEBUG) $(INC_DLL_DEBUG) -c Source\\DLL\\newapi.c -o $(OBJDIR_DLL_DEBUG)\\Source\\DLL\\newapi.o

$(OBJDIR_DLL_DEBUG)\\Source\\DLL\\utl.o: Source\\DLL\\utl.c
	$(CC) $(CFLAGS_DLL_DEBUG) $(INC_DLL_DEBUG) -c Source\\DLL\\utl.c -o $(OBJDIR_DLL_DEBUG)\\Source\\DLL\\utl.o

$(OBJDIR_DLL_DEBUG)\\Source\\DLL\\version.o: Source\\DLL\\version.rc
	$(WINDRES) -i Source\\DLL\\version.rc -J rc -o $(OBJDIR_DLL_DEBUG)\\Source\\DLL\\version.o -O coff $(INC_DLL_DEBUG)

clean_dll_debug: 
	cmd /c del /f $(OBJ_DLL_DEBUG) $(OUT_DLL_DEBUG)
	cmd /c rd Debug\\Win32
	cmd /c rd $(OBJDIR_DLL_DEBUG)\\Source\\DLL

virtual_debug: dll_debug app_debug

.PHONY: before_app after_app clean_app before_dll after_dll clean_dll before_app_debug after_app_debug clean_app_debug before_dll_debug after_dll_debug clean_dll_debug

