#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = i686-w64-mingw32-gcc
CXX = i686-w64-mingw32-g++
AR = ar
LD = i686-w64-mingw32-g++
WINDRES = windres

INC = 
CFLAGS = -fno-ident -Wall -m32 -fvisibility=hidden -D_POSIX=1 -D_POSIX_C_SOURCE=200112L -D__STDC_FORMAT_MACROS -D__USE_MINGW_ANSI_STDIO=0 -D__MINGW_USE_VC2005_COMPAT -DWINVER=0x0501 -DPSAPI_VERSION=1 -D_UNICODE -DUNICODE -DWIN2K_COMPAT
RESINC = 
LIBDIR = 
LIB = -luser32 -ladvapi32 -lcomctl32 -lgdi32 -lpsapi -lwinhttp
LDFLAGS = -static -m32

INC_APP = $(INC)
CFLAGS_APP = $(CFLAGS) -O3 -DNDEBUG
RESINC_APP = $(RESINC)
RCFLAGS_APP = $(RCFLAGS)
LIBDIR_APP = $(LIBDIR)
LIB_APP = $(LIB)
LDFLAGS_APP = $(LDFLAGS) -s
OBJDIR_APP = ..\\.obj\\gcc
DEP_APP = 
OUT_APP = ..\\..\\Release\\misc\\Options.exe

INC_APP_DEBUG = $(INC)
CFLAGS_APP_DEBUG = $(CFLAGS) -Og -g -fno-omit-frame-pointer -D_DEBUG
RESINC_APP_DEBUG = $(RESINC)
RCFLAGS_APP_DEBUG = $(RCFLAGS)
LIBDIR_APP_DEBUG = $(LIBDIR)
LIB_APP_DEBUG = $(LIB)
LDFLAGS_APP_DEBUG = $(LDFLAGS)
OBJDIR_APP_DEBUG = ..\\.obj\\gcc\\dbg
DEP_APP_DEBUG = 
OUT_APP_DEBUG = ..\\..\\Debug\\misc\\Options.exe

OBJ_APP = $(OBJDIR_APP)\\__\\options\\update.o \
	$(OBJDIR_APP)\\__\\options\\resource.o \
	$(OBJDIR_APP)\\__\\options\\main.o \
	$(OBJDIR_APP)\\__\\common\\win2k_compat.o \
	$(OBJDIR_APP)\\__\\common\\utl.o \
	$(OBJDIR_APP)\\__\\common\\newapi.o \
	$(OBJDIR_APP)\\__\\common\\messagebox_custom.o \
	$(OBJDIR_APP)\\__\\common\\getopt_tools.o \
	$(OBJDIR_APP)\\__\\common\\clock.o

OBJ_APP_DEBUG = $(OBJDIR_APP_DEBUG)\\__\\options\\update.o \
	$(OBJDIR_APP_DEBUG)\\__\\options\\resource.o \
	$(OBJDIR_APP_DEBUG)\\__\\options\\main.o \
	$(OBJDIR_APP_DEBUG)\\__\\common\\win2k_compat.o \
	$(OBJDIR_APP_DEBUG)\\__\\common\\utl.o \
	$(OBJDIR_APP_DEBUG)\\__\\common\\newapi.o \
	$(OBJDIR_APP_DEBUG)\\__\\common\\messagebox_custom.o \
	$(OBJDIR_APP_DEBUG)\\__\\common\\getopt_tools.o \
	$(OBJDIR_APP_DEBUG)\\__\\common\\clock.o

all: before_build build_app build_app_debug after_build

clean: clean_app clean_app_debug

before_build: 
	../common/AutoVersion --git . ../common/version.h

after_build: 

before_app: 
	cmd /c if not exist ..\\..\\Release\\misc md ..\\..\\Release\\misc
	cmd /c if not exist $(OBJDIR_APP)\\__\\options md $(OBJDIR_APP)\\__\\options
	cmd /c if not exist $(OBJDIR_APP)\\__\\common md $(OBJDIR_APP)\\__\\common

after_app: 

build_app: before_app out_app after_app

app: before_build build_app after_build

out_app: before_app $(OBJ_APP) $(DEP_APP)
	$(LD) $(LIBDIR_APP) -o $(OUT_APP) $(OBJ_APP)  $(LDFLAGS_APP) $(LIB_APP)

$(OBJDIR_APP)\\__\\options\\update.o: ..\\options\\update.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c ..\\options\\update.c -o $(OBJDIR_APP)\\__\\options\\update.o

$(OBJDIR_APP)\\__\\options\\resource.o: ..\\options\\resource.rc
	$(WINDRES) -i ..\\options\\resource.rc -J rc -o $(OBJDIR_APP)\\__\\options\\resource.o -O coff $(INC_APP)

$(OBJDIR_APP)\\__\\options\\main.o: ..\\options\\main.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c ..\\options\\main.c -o $(OBJDIR_APP)\\__\\options\\main.o

$(OBJDIR_APP)\\__\\common\\win2k_compat.o: ..\\common\\win2k_compat.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c ..\\common\\win2k_compat.c -o $(OBJDIR_APP)\\__\\common\\win2k_compat.o

$(OBJDIR_APP)\\__\\common\\utl.o: ..\\common\\utl.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c ..\\common\\utl.c -o $(OBJDIR_APP)\\__\\common\\utl.o

$(OBJDIR_APP)\\__\\common\\newapi.o: ..\\common\\newapi.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c ..\\common\\newapi.c -o $(OBJDIR_APP)\\__\\common\\newapi.o

$(OBJDIR_APP)\\__\\common\\messagebox_custom.o: ..\\common\\messagebox_custom.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c ..\\common\\messagebox_custom.c -o $(OBJDIR_APP)\\__\\common\\messagebox_custom.o

$(OBJDIR_APP)\\__\\common\\getopt_tools.o: ..\\common\\getopt_tools.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c ..\\common\\getopt_tools.c -o $(OBJDIR_APP)\\__\\common\\getopt_tools.o

$(OBJDIR_APP)\\__\\common\\clock.o: ..\\common\\clock.c
	$(CC) $(CFLAGS_APP) $(INC_APP) -c ..\\common\\clock.c -o $(OBJDIR_APP)\\__\\common\\clock.o

clean_app: 
	cmd /c del /f $(OBJ_APP) $(OUT_APP)
	cmd /c rd $(OBJDIR_APP)\\__\\options
	cmd /c rd $(OBJDIR_APP)\\__\\common

before_app_debug: 
	cmd /c if not exist ..\\..\\Debug\\misc md ..\\..\\Debug\\misc
	cmd /c if not exist $(OBJDIR_APP_DEBUG)\\__\\options md $(OBJDIR_APP_DEBUG)\\__\\options
	cmd /c if not exist $(OBJDIR_APP_DEBUG)\\__\\common md $(OBJDIR_APP_DEBUG)\\__\\common

after_app_debug: 

build_app_debug: before_app_debug out_app_debug after_app_debug

app_debug: before_build build_app_debug after_build

out_app_debug: before_app_debug $(OBJ_APP_DEBUG) $(DEP_APP_DEBUG)
	$(LD) $(LIBDIR_APP_DEBUG) -o $(OUT_APP_DEBUG) $(OBJ_APP_DEBUG)  $(LDFLAGS_APP_DEBUG) $(LIB_APP_DEBUG)

$(OBJDIR_APP_DEBUG)\\__\\options\\update.o: ..\\options\\update.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\options\\update.c -o $(OBJDIR_APP_DEBUG)\\__\\options\\update.o

$(OBJDIR_APP_DEBUG)\\__\\options\\resource.o: ..\\options\\resource.rc
	$(WINDRES) -i ..\\options\\resource.rc -J rc -o $(OBJDIR_APP_DEBUG)\\__\\options\\resource.o -O coff $(INC_APP_DEBUG)

$(OBJDIR_APP_DEBUG)\\__\\options\\main.o: ..\\options\\main.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\options\\main.c -o $(OBJDIR_APP_DEBUG)\\__\\options\\main.o

$(OBJDIR_APP_DEBUG)\\__\\common\\win2k_compat.o: ..\\common\\win2k_compat.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\common\\win2k_compat.c -o $(OBJDIR_APP_DEBUG)\\__\\common\\win2k_compat.o

$(OBJDIR_APP_DEBUG)\\__\\common\\utl.o: ..\\common\\utl.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\common\\utl.c -o $(OBJDIR_APP_DEBUG)\\__\\common\\utl.o

$(OBJDIR_APP_DEBUG)\\__\\common\\newapi.o: ..\\common\\newapi.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\common\\newapi.c -o $(OBJDIR_APP_DEBUG)\\__\\common\\newapi.o

$(OBJDIR_APP_DEBUG)\\__\\common\\messagebox_custom.o: ..\\common\\messagebox_custom.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\common\\messagebox_custom.c -o $(OBJDIR_APP_DEBUG)\\__\\common\\messagebox_custom.o

$(OBJDIR_APP_DEBUG)\\__\\common\\getopt_tools.o: ..\\common\\getopt_tools.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\common\\getopt_tools.c -o $(OBJDIR_APP_DEBUG)\\__\\common\\getopt_tools.o

$(OBJDIR_APP_DEBUG)\\__\\common\\clock.o: ..\\common\\clock.c
	$(CC) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\common\\clock.c -o $(OBJDIR_APP_DEBUG)\\__\\common\\clock.o

clean_app_debug: 
	cmd /c del /f $(OBJ_APP_DEBUG) $(OUT_APP_DEBUG)
	cmd /c rd $(OBJDIR_APP_DEBUG)\\__\\options
	cmd /c rd $(OBJDIR_APP_DEBUG)\\__\\common

.PHONY: before_build after_build before_app after_app clean_app before_app_debug after_app_debug clean_app_debug

