#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC0 = gcc.exe
CXX0 = g++.exe
AR0 = ar.exe
LD0 = g++.exe
WINDRES0 = windres.exe

INC0 = 
CFLAGS0 = -fno-ident -Wall -std=c99 -fvisibility=hidden -D_POSIX=1 -D_POSIX_C_SOURCE=200112L -D__STDC_FORMAT_MACROS -D__USE_MINGW_ANSI_STDIO=0 -D__MINGW_USE_VC2005_COMPAT -DWINVER=0x0501 -DWIN2K_COMPAT
RESINC0 = 
LIBDIR0 = 
LIB0 = -ladvapi32 -luser32 -lole32 -lgdi32 -lpsapi
LDFLAGS0 = -static

CC1 = i686-w64-mingw32-gcc
CXX1 = i686-w64-mingw32-g++
AR1 = ar
LD1 = i686-w64-mingw32-g++
WINDRES1 = windres

INC1 = 
CFLAGS1 = -fno-ident -Wall -std=c99 -fvisibility=hidden -D_POSIX=1 -D_POSIX_C_SOURCE=200112L -D__STDC_FORMAT_MACROS -D__USE_MINGW_ANSI_STDIO=0 -D__MINGW_USE_VC2005_COMPAT -DWINVER=0x0501 -DWIN2K_COMPAT
RESINC1 = 
LIBDIR1 = 
LIB1 = -ladvapi32 -luser32 -lole32 -lgdi32 -lpsapi
LDFLAGS1 = -static

CC2 = x86_64-w64-mingw32-gcc
CXX2 = x86_64-w64-mingw32-g++
AR2 = ar
LD2 = x86_64-w64-mingw32-g++
WINDRES2 = windres

INC2 = 
CFLAGS2 = -fno-ident -Wall -std=c99 -fvisibility=hidden -D_POSIX=1 -D_POSIX_C_SOURCE=200112L -D__STDC_FORMAT_MACROS -D__USE_MINGW_ANSI_STDIO=0 -D__MINGW_USE_VC2005_COMPAT -DWINVER=0x0501 -DWIN2K_COMPAT
RESINC2 = 
LIBDIR2 = 
LIB2 = -ladvapi32 -luser32 -lole32 -lgdi32 -lpsapi
LDFLAGS2 = -static

INC_AUTOVERSION = $(INC0)
CFLAGS_AUTOVERSION =  -Os -Wall -m32 -DNDEBUG
RESINC_AUTOVERSION = $(RESINC0)
RCFLAGS_AUTOVERSION = $(RCFLAGS0)
LIBDIR_AUTOVERSION = $(LIBDIR0)
LIB_AUTOVERSION = $(LIB0)
LDFLAGS_AUTOVERSION =  -s -static -m32
OBJDIR_AUTOVERSION = ..\\.obj
DEP_AUTOVERSION = 
OUT_AUTOVERSION = ..\\common\\AutoVersion.exe

INC_CALENDAR = $(INC1)
CFLAGS_CALENDAR = $(CFLAGS1) -O3 -m32 -DNDEBUG
RESINC_CALENDAR = $(RESINC1)
RCFLAGS_CALENDAR = $(RCFLAGS1)
LIBDIR_CALENDAR = $(LIBDIR1)
LIB_CALENDAR = $(LIB1)-lcomctl32
LDFLAGS_CALENDAR = $(LDFLAGS1) -s -m32
OBJDIR_CALENDAR = ..\\.obj
DEP_CALENDAR = 
OUT_CALENDAR = ..\\..\\Release\\misc\\XPCalendar.exe

INC_CALENDAR_DEBUG = $(INC1)
CFLAGS_CALENDAR_DEBUG = $(CFLAGS1) -m32 -Og -g -fno-omit-frame-pointer -D_DEBUG
RESINC_CALENDAR_DEBUG = $(RESINC1)
RCFLAGS_CALENDAR_DEBUG = $(RCFLAGS1)
LIBDIR_CALENDAR_DEBUG = $(LIBDIR1)
LIB_CALENDAR_DEBUG = $(LIB1)-lcomctl32
LDFLAGS_CALENDAR_DEBUG = $(LDFLAGS1) -m32
OBJDIR_CALENDAR_DEBUG = ..\\.obj\\dbg
DEP_CALENDAR_DEBUG = 
OUT_CALENDAR_DEBUG = ..\\..\\Debug\\misc\\XPCalendar.exe

INC_APP = $(INC1)
CFLAGS_APP = $(CFLAGS1) -O3 -m32 -DNDEBUG
RESINC_APP = $(RESINC1)
RCFLAGS_APP = $(RCFLAGS1)
LIBDIR_APP = $(LIBDIR1)
LIB_APP = $(LIB1)-lcomdlg32 -lshlwapi -lversion -lcomctl32 -lwinmm -lws2_32 -lmpr -luuid -lmsimg32
LDFLAGS_APP = $(LDFLAGS1) -s -m32
OBJDIR_APP = ..\\.obj
DEP_APP = 
OUT_APP = ..\\..\\Release\\Clock.exe

INC_DLL = $(INC1)
CFLAGS_DLL = $(CFLAGS1) -O3 -m32 -DNDEBUG
RESINC_DLL = $(RESINC1)
RCFLAGS_DLL = $(RCFLAGS1)
LIBDIR_DLL = $(LIBDIR1)
LIB_DLL = $(LIB1)
LDFLAGS_DLL = $(LDFLAGS1) -s -m32
OBJDIR_DLL = ..\\.obj
DEP_DLL = 
OUT_DLL = ..\\..\\Release\\misc\\T-Clock.dll

INC_APP_DEBUG = $(INC1)
CFLAGS_APP_DEBUG = $(CFLAGS1) -m32 -Og -g -fno-omit-frame-pointer -D_DEBUG
RESINC_APP_DEBUG = $(RESINC1)
RCFLAGS_APP_DEBUG = $(RCFLAGS1)
LIBDIR_APP_DEBUG = $(LIBDIR1)
LIB_APP_DEBUG = $(LIB1)-lcomdlg32 -lshlwapi -lversion -lcomctl32 -lwinmm -lws2_32 -lmpr -luuid -lmsimg32
LDFLAGS_APP_DEBUG = $(LDFLAGS1) -m32
OBJDIR_APP_DEBUG = ..\\.obj\\dbg
DEP_APP_DEBUG = 
OUT_APP_DEBUG = ..\\..\\Debug\\Clock.exe

INC_DLL_DEBUG = $(INC1)
CFLAGS_DLL_DEBUG = $(CFLAGS1) -m32 -Og -g -fno-omit-frame-pointer -D_DEBUG
RESINC_DLL_DEBUG = $(RESINC1)
RCFLAGS_DLL_DEBUG = $(RCFLAGS1)
LIBDIR_DLL_DEBUG = $(LIBDIR1)
LIB_DLL_DEBUG = $(LIB1)
LDFLAGS_DLL_DEBUG = $(LDFLAGS1) -m32
OBJDIR_DLL_DEBUG = ..\\.obj\\dbg
DEP_DLL_DEBUG = 
OUT_DLL_DEBUG = ..\\..\\Debug\\misc\\T-Clock.dll

INC_APP_64 = $(INC2)
CFLAGS_APP_64 = $(CFLAGS2) -O3 -m64 -DNDEBUG
RESINC_APP_64 = $(RESINC2)
RCFLAGS_APP_64 = $(RCFLAGS2)
LIBDIR_APP_64 = $(LIBDIR2)
LIB_APP_64 = $(LIB2)-lcomdlg32 -lshlwapi -lversion -lcomctl32 -lwinmm -lws2_32 -lmpr -luuid -lmsimg32
LDFLAGS_APP_64 = $(LDFLAGS2) -s -m64
OBJDIR_APP_64 = ..\\.obj64
DEP_APP_64 = 
OUT_APP_64 = ..\\..\\Release\\Clock64.exe

INC_DLL_64 = $(INC2)
CFLAGS_DLL_64 = $(CFLAGS2) -O3 -m64 -DNDEBUG
RESINC_DLL_64 = $(RESINC2)
RCFLAGS_DLL_64 = $(RCFLAGS2)
LIBDIR_DLL_64 = $(LIBDIR2)
LIB_DLL_64 = $(LIB2)
LDFLAGS_DLL_64 = $(LDFLAGS2) -s -m64
OBJDIR_DLL_64 = ..\\.obj64
DEP_DLL_64 = 
OUT_DLL_64 = ..\\..\\Release\\misc\\T-Clock64.dll

INC_APP_64_DEBUG = $(INC2)
CFLAGS_APP_64_DEBUG = $(CFLAGS2) -m64 -Og -g -fno-omit-frame-pointer -D_DEBUG
RESINC_APP_64_DEBUG = $(RESINC2)
RCFLAGS_APP_64_DEBUG = $(RCFLAGS2)
LIBDIR_APP_64_DEBUG = $(LIBDIR2)
LIB_APP_64_DEBUG = $(LIB2)-lcomdlg32 -lshlwapi -lversion -lcomctl32 -lwinmm -lws2_32 -lmpr -luuid -lmsimg32
LDFLAGS_APP_64_DEBUG = $(LDFLAGS2) -m64
OBJDIR_APP_64_DEBUG = ..\\.obj64\\dbg
DEP_APP_64_DEBUG = 
OUT_APP_64_DEBUG = ..\\..\\Debug\\Clock64.exe

INC_DLL_64_DEBUG = $(INC2)
CFLAGS_DLL_64_DEBUG = $(CFLAGS2) -m64 -Og -g -fno-omit-frame-pointer -D_DEBUG
RESINC_DLL_64_DEBUG = $(RESINC2)
RCFLAGS_DLL_64_DEBUG = $(RCFLAGS2)
LIBDIR_DLL_64_DEBUG = $(LIBDIR2)
LIB_DLL_64_DEBUG = $(LIB2)
LDFLAGS_DLL_64_DEBUG = $(LDFLAGS2) -m64
OBJDIR_DLL_64_DEBUG = ..\\.obj64\\dbg
DEP_DLL_64_DEBUG = 
OUT_DLL_64_DEBUG = ..\\..\\Debug\\misc\\T-Clock64.dll

OBJ_AUTOVERSION = $(OBJDIR_AUTOVERSION)\\__\\common\\autoversion.o

OBJ_CALENDAR = $(OBJDIR_CALENDAR)\\__\\common\\clock.o \
	$(OBJDIR_CALENDAR)\\__\\common\\newapi.o \
	$(OBJDIR_CALENDAR)\\__\\common\\utl.o \
	$(OBJDIR_CALENDAR)\\__\\common\\win2k_compat.o \
	$(OBJDIR_CALENDAR)\\__\\Calendar\\DeskCalendar.o \
	$(OBJDIR_CALENDAR)\\__\\Calendar\\resource.o

OBJ_CALENDAR_DEBUG = $(OBJDIR_CALENDAR_DEBUG)\\__\\common\\clock.o \
	$(OBJDIR_CALENDAR_DEBUG)\\__\\common\\newapi.o \
	$(OBJDIR_CALENDAR_DEBUG)\\__\\common\\utl.o \
	$(OBJDIR_CALENDAR_DEBUG)\\__\\common\\win2k_compat.o \
	$(OBJDIR_CALENDAR_DEBUG)\\__\\Calendar\\DeskCalendar.o \
	$(OBJDIR_CALENDAR_DEBUG)\\__\\Calendar\\resource.o

OBJ_APP = $(OBJDIR_APP)\\__\\common\\HaveSetTimePerms.o \
	$(OBJDIR_APP)\\__\\common\\clock.o \
	$(OBJDIR_APP)\\__\\common\\control_extensions.o \
	$(OBJDIR_APP)\\__\\common\\newapi.o \
	$(OBJDIR_APP)\\__\\common\\utl.o \
	$(OBJDIR_APP)\\__\\common\\win2k_compat.o \
	$(OBJDIR_APP)\\__\\Clock\\BounceWind.o \
	$(OBJDIR_APP)\\__\\Clock\\ExitWindows.o \
	$(OBJDIR_APP)\\__\\Clock\\PageHotKey.o \
	$(OBJDIR_APP)\\__\\Clock\\PageMisc.o \
	$(OBJDIR_APP)\\__\\Clock\\PageMouse.o \
	$(OBJDIR_APP)\\__\\Clock\\PageQuicky.o \
	$(OBJDIR_APP)\\__\\Clock\\PageQuickyMenu.o \
	$(OBJDIR_APP)\\__\\Clock\\SNTP.o \
	$(OBJDIR_APP)\\__\\Clock\\StopWatch.o \
	$(OBJDIR_APP)\\__\\Clock\\alarm.o \
	$(OBJDIR_APP)\\__\\Clock\\alarmday.o \
	$(OBJDIR_APP)\\__\\Clock\\main.o \
	$(OBJDIR_APP)\\__\\Clock\\menu.o \
	$(OBJDIR_APP)\\__\\Clock\\mouse.o \
	$(OBJDIR_APP)\\__\\Clock\\pageabout.o \
	$(OBJDIR_APP)\\__\\Clock\\pagealarm.o \
	$(OBJDIR_APP)\\__\\Clock\\pagecolor.o \
	$(OBJDIR_APP)\\__\\Clock\\pageformat.o \
	$(OBJDIR_APP)\\__\\Clock\\propsheet.o \
	$(OBJDIR_APP)\\__\\Clock\\settings.o \
	$(OBJDIR_APP)\\__\\Clock\\soundselect.o \
	$(OBJDIR_APP)\\__\\Clock\\tClock.o \
	$(OBJDIR_APP)\\__\\Clock\\timer.o

OBJ_DLL = $(OBJDIR_DLL)\\__\\DLL\\Tclock.o \
	$(OBJDIR_DLL)\\__\\DLL\\clock_api.o \
	$(OBJDIR_DLL)\\__\\DLL\\clock_color.o \
	$(OBJDIR_DLL)\\__\\DLL\\clock_utils.o \
	$(OBJDIR_DLL)\\__\\DLL\\font.o \
	$(OBJDIR_DLL)\\__\\DLL\\format.o \
	$(OBJDIR_DLL)\\__\\DLL\\main.o \
	$(OBJDIR_DLL)\\__\\DLL\\version.o \
	$(OBJDIR_DLL)\\__\\common\\newapi.o \
	$(OBJDIR_DLL)\\__\\common\\utl.o \
	$(OBJDIR_DLL)\\__\\common\\win2k_compat.o

OBJ_APP_DEBUG = $(OBJDIR_APP_DEBUG)\\__\\common\\HaveSetTimePerms.o \
	$(OBJDIR_APP_DEBUG)\\__\\common\\clock.o \
	$(OBJDIR_APP_DEBUG)\\__\\common\\control_extensions.o \
	$(OBJDIR_APP_DEBUG)\\__\\common\\newapi.o \
	$(OBJDIR_APP_DEBUG)\\__\\common\\utl.o \
	$(OBJDIR_APP_DEBUG)\\__\\common\\win2k_compat.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\BounceWind.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\ExitWindows.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\PageHotKey.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\PageMisc.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\PageMouse.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\PageQuicky.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\PageQuickyMenu.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\SNTP.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\StopWatch.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\alarm.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\alarmday.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\main.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\menu.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\mouse.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\pageabout.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\pagealarm.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\pagecolor.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\pageformat.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\propsheet.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\settings.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\soundselect.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\tClock.o \
	$(OBJDIR_APP_DEBUG)\\__\\Clock\\timer.o

OBJ_DLL_DEBUG = $(OBJDIR_DLL_DEBUG)\\__\\DLL\\Tclock.o \
	$(OBJDIR_DLL_DEBUG)\\__\\DLL\\clock_api.o \
	$(OBJDIR_DLL_DEBUG)\\__\\DLL\\clock_color.o \
	$(OBJDIR_DLL_DEBUG)\\__\\DLL\\clock_utils.o \
	$(OBJDIR_DLL_DEBUG)\\__\\DLL\\font.o \
	$(OBJDIR_DLL_DEBUG)\\__\\DLL\\format.o \
	$(OBJDIR_DLL_DEBUG)\\__\\DLL\\main.o \
	$(OBJDIR_DLL_DEBUG)\\__\\DLL\\version.o \
	$(OBJDIR_DLL_DEBUG)\\__\\common\\newapi.o \
	$(OBJDIR_DLL_DEBUG)\\__\\common\\utl.o \
	$(OBJDIR_DLL_DEBUG)\\__\\common\\win2k_compat.o

OBJ_APP_64 = $(OBJDIR_APP_64)\\__\\common\\HaveSetTimePerms.o \
	$(OBJDIR_APP_64)\\__\\common\\clock.o \
	$(OBJDIR_APP_64)\\__\\common\\control_extensions.o \
	$(OBJDIR_APP_64)\\__\\common\\newapi.o \
	$(OBJDIR_APP_64)\\__\\common\\utl.o \
	$(OBJDIR_APP_64)\\__\\common\\win2k_compat.o \
	$(OBJDIR_APP_64)\\__\\Clock\\BounceWind.o \
	$(OBJDIR_APP_64)\\__\\Clock\\ExitWindows.o \
	$(OBJDIR_APP_64)\\__\\Clock\\PageHotKey.o \
	$(OBJDIR_APP_64)\\__\\Clock\\PageMisc.o \
	$(OBJDIR_APP_64)\\__\\Clock\\PageMouse.o \
	$(OBJDIR_APP_64)\\__\\Clock\\PageQuicky.o \
	$(OBJDIR_APP_64)\\__\\Clock\\PageQuickyMenu.o \
	$(OBJDIR_APP_64)\\__\\Clock\\SNTP.o \
	$(OBJDIR_APP_64)\\__\\Clock\\StopWatch.o \
	$(OBJDIR_APP_64)\\__\\Clock\\alarm.o \
	$(OBJDIR_APP_64)\\__\\Clock\\alarmday.o \
	$(OBJDIR_APP_64)\\__\\Clock\\main.o \
	$(OBJDIR_APP_64)\\__\\Clock\\menu.o \
	$(OBJDIR_APP_64)\\__\\Clock\\mouse.o \
	$(OBJDIR_APP_64)\\__\\Clock\\pageabout.o \
	$(OBJDIR_APP_64)\\__\\Clock\\pagealarm.o \
	$(OBJDIR_APP_64)\\__\\Clock\\pagecolor.o \
	$(OBJDIR_APP_64)\\__\\Clock\\pageformat.o \
	$(OBJDIR_APP_64)\\__\\Clock\\propsheet.o \
	$(OBJDIR_APP_64)\\__\\Clock\\settings.o \
	$(OBJDIR_APP_64)\\__\\Clock\\soundselect.o \
	$(OBJDIR_APP_64)\\__\\Clock\\tClock.o \
	$(OBJDIR_APP_64)\\__\\Clock\\timer.o

OBJ_DLL_64 = $(OBJDIR_DLL_64)\\__\\DLL\\Tclock.o \
	$(OBJDIR_DLL_64)\\__\\DLL\\clock_api.o \
	$(OBJDIR_DLL_64)\\__\\DLL\\clock_color.o \
	$(OBJDIR_DLL_64)\\__\\DLL\\clock_utils.o \
	$(OBJDIR_DLL_64)\\__\\DLL\\font.o \
	$(OBJDIR_DLL_64)\\__\\DLL\\format.o \
	$(OBJDIR_DLL_64)\\__\\DLL\\main.o \
	$(OBJDIR_DLL_64)\\__\\DLL\\version.o \
	$(OBJDIR_DLL_64)\\__\\common\\newapi.o \
	$(OBJDIR_DLL_64)\\__\\common\\utl.o \
	$(OBJDIR_DLL_64)\\__\\common\\win2k_compat.o

OBJ_APP_64_DEBUG = $(OBJDIR_APP_64_DEBUG)\\__\\common\\HaveSetTimePerms.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\common\\clock.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\common\\control_extensions.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\common\\newapi.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\common\\utl.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\common\\win2k_compat.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\BounceWind.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\ExitWindows.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\PageHotKey.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\PageMisc.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\PageMouse.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\PageQuicky.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\PageQuickyMenu.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\SNTP.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\StopWatch.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\alarm.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\alarmday.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\main.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\menu.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\mouse.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\pageabout.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\pagealarm.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\pagecolor.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\pageformat.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\propsheet.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\settings.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\soundselect.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\tClock.o \
	$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\timer.o

OBJ_DLL_64_DEBUG = $(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\Tclock.o \
	$(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\clock_api.o \
	$(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\clock_color.o \
	$(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\clock_utils.o \
	$(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\font.o \
	$(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\format.o \
	$(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\main.o \
	$(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\version.o \
	$(OBJDIR_DLL_64_DEBUG)\\__\\common\\newapi.o \
	$(OBJDIR_DLL_64_DEBUG)\\__\\common\\utl.o \
	$(OBJDIR_DLL_64_DEBUG)\\__\\common\\win2k_compat.o

all: autoversion calendar calendar_debug app dll app_debug dll_debug app_64 dll_64 app_64_debug dll_64_debug

clean: clean_autoversion clean_calendar clean_calendar_debug clean_app clean_dll clean_app_debug clean_dll_debug clean_app_64 clean_dll_64 clean_app_64_debug clean_dll_64_debug

before_autoversion: 
	cmd /c if not exist ..\\common md ..\\common
	cmd /c if not exist $(OBJDIR_AUTOVERSION)\\__\\common md $(OBJDIR_AUTOVERSION)\\__\\common

after_autoversion: 

autoversion: before_autoversion out_autoversion after_autoversion

out_autoversion: before_autoversion $(OBJ_AUTOVERSION) $(DEP_AUTOVERSION)
	$(LD0) $(LIBDIR_AUTOVERSION) -o $(OUT_AUTOVERSION) $(OBJ_AUTOVERSION)  $(LDFLAGS_AUTOVERSION) $(LIB_AUTOVERSION)

$(OBJDIR_AUTOVERSION)\\__\\common\\autoversion.o: ..\\common\\autoversion.cpp
	$(CXX0) $(CFLAGS_AUTOVERSION) $(INC_AUTOVERSION) -c ..\\common\\autoversion.cpp -o $(OBJDIR_AUTOVERSION)\\__\\common\\autoversion.o

clean_autoversion: 
	cmd /c del /f $(OBJ_AUTOVERSION) $(OUT_AUTOVERSION)
	cmd /c rd $(OBJDIR_AUTOVERSION)\\__\\common

before_calendar: 
	../common/AutoVersion --git . ../common/version.h
	cmd /c if not exist ..\\..\\Release\\misc md ..\\..\\Release\\misc
	cmd /c if not exist $(OBJDIR_CALENDAR)\\__\\common md $(OBJDIR_CALENDAR)\\__\\common
	cmd /c if not exist $(OBJDIR_CALENDAR)\\__\\Calendar md $(OBJDIR_CALENDAR)\\__\\Calendar

after_calendar: 

calendar: before_calendar out_calendar after_calendar

out_calendar: before_calendar $(OBJ_CALENDAR) $(DEP_CALENDAR)
	$(LD1) $(LIBDIR_CALENDAR) -o $(OUT_CALENDAR) $(OBJ_CALENDAR)  $(LDFLAGS_CALENDAR) -mwindows $(LIB_CALENDAR)

$(OBJDIR_CALENDAR)\\__\\common\\clock.o: ..\\common\\clock.c
	$(CC1) $(CFLAGS_CALENDAR) $(INC_CALENDAR) -c ..\\common\\clock.c -o $(OBJDIR_CALENDAR)\\__\\common\\clock.o

$(OBJDIR_CALENDAR)\\__\\common\\newapi.o: ..\\common\\newapi.c
	$(CC1) $(CFLAGS_CALENDAR) $(INC_CALENDAR) -c ..\\common\\newapi.c -o $(OBJDIR_CALENDAR)\\__\\common\\newapi.o

$(OBJDIR_CALENDAR)\\__\\common\\utl.o: ..\\common\\utl.c
	$(CC1) $(CFLAGS_CALENDAR) $(INC_CALENDAR) -c ..\\common\\utl.c -o $(OBJDIR_CALENDAR)\\__\\common\\utl.o

$(OBJDIR_CALENDAR)\\__\\common\\win2k_compat.o: ..\\common\\win2k_compat.c
	$(CC1) $(CFLAGS_CALENDAR) $(INC_CALENDAR) -c ..\\common\\win2k_compat.c -o $(OBJDIR_CALENDAR)\\__\\common\\win2k_compat.o

$(OBJDIR_CALENDAR)\\__\\Calendar\\DeskCalendar.o: ..\\Calendar\\DeskCalendar.c
	$(CC1) $(CFLAGS_CALENDAR) $(INC_CALENDAR) -c ..\\Calendar\\DeskCalendar.c -o $(OBJDIR_CALENDAR)\\__\\Calendar\\DeskCalendar.o

$(OBJDIR_CALENDAR)\\__\\Calendar\\resource.o: ..\\Calendar\\resource.rc
	$(WINDRES1) -i ..\\Calendar\\resource.rc -J rc -o $(OBJDIR_CALENDAR)\\__\\Calendar\\resource.o -O coff $(INC_CALENDAR)

clean_calendar: 
	cmd /c del /f $(OBJ_CALENDAR) $(OUT_CALENDAR)
	cmd /c rd $(OBJDIR_CALENDAR)\\__\\common
	cmd /c rd $(OBJDIR_CALENDAR)\\__\\Calendar

before_calendar_debug: 
	../common/AutoVersion --git . ../common/version.h
	cmd /c if not exist ..\\..\\Debug\\misc md ..\\..\\Debug\\misc
	cmd /c if not exist $(OBJDIR_CALENDAR_DEBUG)\\__\\common md $(OBJDIR_CALENDAR_DEBUG)\\__\\common
	cmd /c if not exist $(OBJDIR_CALENDAR_DEBUG)\\__\\Calendar md $(OBJDIR_CALENDAR_DEBUG)\\__\\Calendar

after_calendar_debug: 
	objcopy --only-keep-debug ../../Debug/misc/XPCalendar.exe ../../Debug/misc/XPCalendar.dbg
	objcopy --strip-debug --strip-unneeded --add-gnu-debuglink=../../Debug/misc/XPCalendar.dbg ../../Debug/misc/XPCalendar.exe

calendar_debug: before_calendar_debug out_calendar_debug after_calendar_debug

out_calendar_debug: before_calendar_debug $(OBJ_CALENDAR_DEBUG) $(DEP_CALENDAR_DEBUG)
	$(LD1) $(LIBDIR_CALENDAR_DEBUG) -o $(OUT_CALENDAR_DEBUG) $(OBJ_CALENDAR_DEBUG)  $(LDFLAGS_CALENDAR_DEBUG) -mwindows $(LIB_CALENDAR_DEBUG)

$(OBJDIR_CALENDAR_DEBUG)\\__\\common\\clock.o: ..\\common\\clock.c
	$(CC1) $(CFLAGS_CALENDAR_DEBUG) $(INC_CALENDAR_DEBUG) -c ..\\common\\clock.c -o $(OBJDIR_CALENDAR_DEBUG)\\__\\common\\clock.o

$(OBJDIR_CALENDAR_DEBUG)\\__\\common\\newapi.o: ..\\common\\newapi.c
	$(CC1) $(CFLAGS_CALENDAR_DEBUG) $(INC_CALENDAR_DEBUG) -c ..\\common\\newapi.c -o $(OBJDIR_CALENDAR_DEBUG)\\__\\common\\newapi.o

$(OBJDIR_CALENDAR_DEBUG)\\__\\common\\utl.o: ..\\common\\utl.c
	$(CC1) $(CFLAGS_CALENDAR_DEBUG) $(INC_CALENDAR_DEBUG) -c ..\\common\\utl.c -o $(OBJDIR_CALENDAR_DEBUG)\\__\\common\\utl.o

$(OBJDIR_CALENDAR_DEBUG)\\__\\common\\win2k_compat.o: ..\\common\\win2k_compat.c
	$(CC1) $(CFLAGS_CALENDAR_DEBUG) $(INC_CALENDAR_DEBUG) -c ..\\common\\win2k_compat.c -o $(OBJDIR_CALENDAR_DEBUG)\\__\\common\\win2k_compat.o

$(OBJDIR_CALENDAR_DEBUG)\\__\\Calendar\\DeskCalendar.o: ..\\Calendar\\DeskCalendar.c
	$(CC1) $(CFLAGS_CALENDAR_DEBUG) $(INC_CALENDAR_DEBUG) -c ..\\Calendar\\DeskCalendar.c -o $(OBJDIR_CALENDAR_DEBUG)\\__\\Calendar\\DeskCalendar.o

$(OBJDIR_CALENDAR_DEBUG)\\__\\Calendar\\resource.o: ..\\Calendar\\resource.rc
	$(WINDRES1) -i ..\\Calendar\\resource.rc -J rc -o $(OBJDIR_CALENDAR_DEBUG)\\__\\Calendar\\resource.o -O coff $(INC_CALENDAR_DEBUG)

clean_calendar_debug: 
	cmd /c del /f $(OBJ_CALENDAR_DEBUG) $(OUT_CALENDAR_DEBUG)
	cmd /c rd $(OBJDIR_CALENDAR_DEBUG)\\__\\common
	cmd /c rd $(OBJDIR_CALENDAR_DEBUG)\\__\\Calendar

before_app: 
	../common/AutoVersion --git . ../common/version.h
	cmd /c if not exist ..\\..\\Release md ..\\..\\Release
	cmd /c if not exist $(OBJDIR_APP)\\__\\common md $(OBJDIR_APP)\\__\\common
	cmd /c if not exist $(OBJDIR_APP)\\__\\Clock md $(OBJDIR_APP)\\__\\Clock

after_app: 

app: before_app out_app after_app

out_app: before_app $(OBJ_APP) $(DEP_APP)
	$(LD1) $(LIBDIR_APP) -o $(OUT_APP) $(OBJ_APP)  $(LDFLAGS_APP) -mwindows $(LIB_APP)

$(OBJDIR_APP)\\__\\common\\HaveSetTimePerms.o: ..\\common\\HaveSetTimePerms.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\common\\HaveSetTimePerms.c -o $(OBJDIR_APP)\\__\\common\\HaveSetTimePerms.o

$(OBJDIR_APP)\\__\\common\\clock.o: ..\\common\\clock.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\common\\clock.c -o $(OBJDIR_APP)\\__\\common\\clock.o

$(OBJDIR_APP)\\__\\common\\control_extensions.o: ..\\common\\control_extensions.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\common\\control_extensions.c -o $(OBJDIR_APP)\\__\\common\\control_extensions.o

$(OBJDIR_APP)\\__\\common\\newapi.o: ..\\common\\newapi.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\common\\newapi.c -o $(OBJDIR_APP)\\__\\common\\newapi.o

$(OBJDIR_APP)\\__\\common\\utl.o: ..\\common\\utl.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\common\\utl.c -o $(OBJDIR_APP)\\__\\common\\utl.o

$(OBJDIR_APP)\\__\\common\\win2k_compat.o: ..\\common\\win2k_compat.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\common\\win2k_compat.c -o $(OBJDIR_APP)\\__\\common\\win2k_compat.o

$(OBJDIR_APP)\\__\\Clock\\BounceWind.o: ..\\Clock\\BounceWind.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\Clock\\BounceWind.c -o $(OBJDIR_APP)\\__\\Clock\\BounceWind.o

$(OBJDIR_APP)\\__\\Clock\\ExitWindows.o: ..\\Clock\\ExitWindows.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\Clock\\ExitWindows.c -o $(OBJDIR_APP)\\__\\Clock\\ExitWindows.o

$(OBJDIR_APP)\\__\\Clock\\PageHotKey.o: ..\\Clock\\PageHotKey.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\Clock\\PageHotKey.c -o $(OBJDIR_APP)\\__\\Clock\\PageHotKey.o

$(OBJDIR_APP)\\__\\Clock\\PageMisc.o: ..\\Clock\\PageMisc.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\Clock\\PageMisc.c -o $(OBJDIR_APP)\\__\\Clock\\PageMisc.o

$(OBJDIR_APP)\\__\\Clock\\PageMouse.o: ..\\Clock\\PageMouse.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\Clock\\PageMouse.c -o $(OBJDIR_APP)\\__\\Clock\\PageMouse.o

$(OBJDIR_APP)\\__\\Clock\\PageQuicky.o: ..\\Clock\\PageQuicky.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\Clock\\PageQuicky.c -o $(OBJDIR_APP)\\__\\Clock\\PageQuicky.o

$(OBJDIR_APP)\\__\\Clock\\PageQuickyMenu.o: ..\\Clock\\PageQuickyMenu.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\Clock\\PageQuickyMenu.c -o $(OBJDIR_APP)\\__\\Clock\\PageQuickyMenu.o

$(OBJDIR_APP)\\__\\Clock\\SNTP.o: ..\\Clock\\SNTP.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\Clock\\SNTP.c -o $(OBJDIR_APP)\\__\\Clock\\SNTP.o

$(OBJDIR_APP)\\__\\Clock\\StopWatch.o: ..\\Clock\\StopWatch.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\Clock\\StopWatch.c -o $(OBJDIR_APP)\\__\\Clock\\StopWatch.o

$(OBJDIR_APP)\\__\\Clock\\alarm.o: ..\\Clock\\alarm.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\Clock\\alarm.c -o $(OBJDIR_APP)\\__\\Clock\\alarm.o

$(OBJDIR_APP)\\__\\Clock\\alarmday.o: ..\\Clock\\alarmday.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\Clock\\alarmday.c -o $(OBJDIR_APP)\\__\\Clock\\alarmday.o

$(OBJDIR_APP)\\__\\Clock\\main.o: ..\\Clock\\main.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\Clock\\main.c -o $(OBJDIR_APP)\\__\\Clock\\main.o

$(OBJDIR_APP)\\__\\Clock\\menu.o: ..\\Clock\\menu.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\Clock\\menu.c -o $(OBJDIR_APP)\\__\\Clock\\menu.o

$(OBJDIR_APP)\\__\\Clock\\mouse.o: ..\\Clock\\mouse.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\Clock\\mouse.c -o $(OBJDIR_APP)\\__\\Clock\\mouse.o

$(OBJDIR_APP)\\__\\Clock\\pageabout.o: ..\\Clock\\pageabout.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\Clock\\pageabout.c -o $(OBJDIR_APP)\\__\\Clock\\pageabout.o

$(OBJDIR_APP)\\__\\Clock\\pagealarm.o: ..\\Clock\\pagealarm.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\Clock\\pagealarm.c -o $(OBJDIR_APP)\\__\\Clock\\pagealarm.o

$(OBJDIR_APP)\\__\\Clock\\pagecolor.o: ..\\Clock\\pagecolor.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\Clock\\pagecolor.c -o $(OBJDIR_APP)\\__\\Clock\\pagecolor.o

$(OBJDIR_APP)\\__\\Clock\\pageformat.o: ..\\Clock\\pageformat.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\Clock\\pageformat.c -o $(OBJDIR_APP)\\__\\Clock\\pageformat.o

$(OBJDIR_APP)\\__\\Clock\\propsheet.o: ..\\Clock\\propsheet.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\Clock\\propsheet.c -o $(OBJDIR_APP)\\__\\Clock\\propsheet.o

$(OBJDIR_APP)\\__\\Clock\\settings.o: ..\\Clock\\settings.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\Clock\\settings.c -o $(OBJDIR_APP)\\__\\Clock\\settings.o

$(OBJDIR_APP)\\__\\Clock\\soundselect.o: ..\\Clock\\soundselect.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\Clock\\soundselect.c -o $(OBJDIR_APP)\\__\\Clock\\soundselect.o

$(OBJDIR_APP)\\__\\Clock\\tClock.o: ..\\Clock\\tClock.rc
	$(WINDRES1) -i ..\\Clock\\tClock.rc -J rc -o $(OBJDIR_APP)\\__\\Clock\\tClock.o -O coff $(INC_APP)

$(OBJDIR_APP)\\__\\Clock\\timer.o: ..\\Clock\\timer.c
	$(CC1) $(CFLAGS_APP) $(INC_APP) -c ..\\Clock\\timer.c -o $(OBJDIR_APP)\\__\\Clock\\timer.o

clean_app: 
	cmd /c del /f $(OBJ_APP) $(OUT_APP)
	cmd /c rd $(OBJDIR_APP)\\__\\common
	cmd /c rd $(OBJDIR_APP)\\__\\Clock

before_dll: 
	../common/AutoVersion --git . ../common/version.h
	cmd /c if not exist ..\\..\\Release\\misc md ..\\..\\Release\\misc
	cmd /c if not exist $(OBJDIR_DLL)\\__\\DLL md $(OBJDIR_DLL)\\__\\DLL
	cmd /c if not exist $(OBJDIR_DLL)\\__\\common md $(OBJDIR_DLL)\\__\\common

after_dll: 

dll: before_dll out_dll after_dll

out_dll: before_dll $(OBJ_DLL) $(DEP_DLL)
	$(LD1) -shared $(LIBDIR_DLL) $(OBJ_DLL)  -o $(OUT_DLL) $(LDFLAGS_DLL) $(LIB_DLL)

$(OBJDIR_DLL)\\__\\DLL\\Tclock.o: ..\\DLL\\Tclock.c
	$(CC1) $(CFLAGS_DLL) $(INC_DLL) -c ..\\DLL\\Tclock.c -o $(OBJDIR_DLL)\\__\\DLL\\Tclock.o

$(OBJDIR_DLL)\\__\\DLL\\clock_api.o: ..\\DLL\\clock_api.c
	$(CC1) $(CFLAGS_DLL) $(INC_DLL) -c ..\\DLL\\clock_api.c -o $(OBJDIR_DLL)\\__\\DLL\\clock_api.o

$(OBJDIR_DLL)\\__\\DLL\\clock_color.o: ..\\DLL\\clock_color.c
	$(CC1) $(CFLAGS_DLL) $(INC_DLL) -c ..\\DLL\\clock_color.c -o $(OBJDIR_DLL)\\__\\DLL\\clock_color.o

$(OBJDIR_DLL)\\__\\DLL\\clock_utils.o: ..\\DLL\\clock_utils.c
	$(CC1) $(CFLAGS_DLL) $(INC_DLL) -c ..\\DLL\\clock_utils.c -o $(OBJDIR_DLL)\\__\\DLL\\clock_utils.o

$(OBJDIR_DLL)\\__\\DLL\\font.o: ..\\DLL\\font.c
	$(CC1) $(CFLAGS_DLL) $(INC_DLL) -c ..\\DLL\\font.c -o $(OBJDIR_DLL)\\__\\DLL\\font.o

$(OBJDIR_DLL)\\__\\DLL\\format.o: ..\\DLL\\format.c
	$(CC1) $(CFLAGS_DLL) $(INC_DLL) -c ..\\DLL\\format.c -o $(OBJDIR_DLL)\\__\\DLL\\format.o

$(OBJDIR_DLL)\\__\\DLL\\main.o: ..\\DLL\\main.c
	$(CC1) $(CFLAGS_DLL) $(INC_DLL) -c ..\\DLL\\main.c -o $(OBJDIR_DLL)\\__\\DLL\\main.o

$(OBJDIR_DLL)\\__\\DLL\\version.o: ..\\DLL\\version.rc
	$(WINDRES1) -i ..\\DLL\\version.rc -J rc -o $(OBJDIR_DLL)\\__\\DLL\\version.o -O coff $(INC_DLL)

$(OBJDIR_DLL)\\__\\common\\newapi.o: ..\\common\\newapi.c
	$(CC1) $(CFLAGS_DLL) $(INC_DLL) -c ..\\common\\newapi.c -o $(OBJDIR_DLL)\\__\\common\\newapi.o

$(OBJDIR_DLL)\\__\\common\\utl.o: ..\\common\\utl.c
	$(CC1) $(CFLAGS_DLL) $(INC_DLL) -c ..\\common\\utl.c -o $(OBJDIR_DLL)\\__\\common\\utl.o

$(OBJDIR_DLL)\\__\\common\\win2k_compat.o: ..\\common\\win2k_compat.c
	$(CC1) $(CFLAGS_DLL) $(INC_DLL) -c ..\\common\\win2k_compat.c -o $(OBJDIR_DLL)\\__\\common\\win2k_compat.o

clean_dll: 
	cmd /c del /f $(OBJ_DLL) $(OUT_DLL)
	cmd /c rd $(OBJDIR_DLL)\\__\\DLL
	cmd /c rd $(OBJDIR_DLL)\\__\\common

before_app_debug: 
	../common/AutoVersion --git . ../common/version.h
	cmd /c if not exist ..\\..\\Debug md ..\\..\\Debug
	cmd /c if not exist $(OBJDIR_APP_DEBUG)\\__\\common md $(OBJDIR_APP_DEBUG)\\__\\common
	cmd /c if not exist $(OBJDIR_APP_DEBUG)\\__\\Clock md $(OBJDIR_APP_DEBUG)\\__\\Clock

after_app_debug: 
	objcopy --only-keep-debug ../../Debug/Clock.exe ../../Debug/Clock.dbg
	objcopy --strip-debug --strip-unneeded --add-gnu-debuglink=../../Debug/Clock.dbg ../../Debug/Clock.exe

app_debug: before_app_debug out_app_debug after_app_debug

out_app_debug: before_app_debug $(OBJ_APP_DEBUG) $(DEP_APP_DEBUG)
	$(LD1) $(LIBDIR_APP_DEBUG) -o $(OUT_APP_DEBUG) $(OBJ_APP_DEBUG)  $(LDFLAGS_APP_DEBUG) -mwindows $(LIB_APP_DEBUG)

$(OBJDIR_APP_DEBUG)\\__\\common\\HaveSetTimePerms.o: ..\\common\\HaveSetTimePerms.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\common\\HaveSetTimePerms.c -o $(OBJDIR_APP_DEBUG)\\__\\common\\HaveSetTimePerms.o

$(OBJDIR_APP_DEBUG)\\__\\common\\clock.o: ..\\common\\clock.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\common\\clock.c -o $(OBJDIR_APP_DEBUG)\\__\\common\\clock.o

$(OBJDIR_APP_DEBUG)\\__\\common\\control_extensions.o: ..\\common\\control_extensions.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\common\\control_extensions.c -o $(OBJDIR_APP_DEBUG)\\__\\common\\control_extensions.o

$(OBJDIR_APP_DEBUG)\\__\\common\\newapi.o: ..\\common\\newapi.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\common\\newapi.c -o $(OBJDIR_APP_DEBUG)\\__\\common\\newapi.o

$(OBJDIR_APP_DEBUG)\\__\\common\\utl.o: ..\\common\\utl.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\common\\utl.c -o $(OBJDIR_APP_DEBUG)\\__\\common\\utl.o

$(OBJDIR_APP_DEBUG)\\__\\common\\win2k_compat.o: ..\\common\\win2k_compat.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\common\\win2k_compat.c -o $(OBJDIR_APP_DEBUG)\\__\\common\\win2k_compat.o

$(OBJDIR_APP_DEBUG)\\__\\Clock\\BounceWind.o: ..\\Clock\\BounceWind.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\Clock\\BounceWind.c -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\BounceWind.o

$(OBJDIR_APP_DEBUG)\\__\\Clock\\ExitWindows.o: ..\\Clock\\ExitWindows.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\Clock\\ExitWindows.c -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\ExitWindows.o

$(OBJDIR_APP_DEBUG)\\__\\Clock\\PageHotKey.o: ..\\Clock\\PageHotKey.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\Clock\\PageHotKey.c -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\PageHotKey.o

$(OBJDIR_APP_DEBUG)\\__\\Clock\\PageMisc.o: ..\\Clock\\PageMisc.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\Clock\\PageMisc.c -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\PageMisc.o

$(OBJDIR_APP_DEBUG)\\__\\Clock\\PageMouse.o: ..\\Clock\\PageMouse.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\Clock\\PageMouse.c -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\PageMouse.o

$(OBJDIR_APP_DEBUG)\\__\\Clock\\PageQuicky.o: ..\\Clock\\PageQuicky.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\Clock\\PageQuicky.c -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\PageQuicky.o

$(OBJDIR_APP_DEBUG)\\__\\Clock\\PageQuickyMenu.o: ..\\Clock\\PageQuickyMenu.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\Clock\\PageQuickyMenu.c -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\PageQuickyMenu.o

$(OBJDIR_APP_DEBUG)\\__\\Clock\\SNTP.o: ..\\Clock\\SNTP.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\Clock\\SNTP.c -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\SNTP.o

$(OBJDIR_APP_DEBUG)\\__\\Clock\\StopWatch.o: ..\\Clock\\StopWatch.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\Clock\\StopWatch.c -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\StopWatch.o

$(OBJDIR_APP_DEBUG)\\__\\Clock\\alarm.o: ..\\Clock\\alarm.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\Clock\\alarm.c -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\alarm.o

$(OBJDIR_APP_DEBUG)\\__\\Clock\\alarmday.o: ..\\Clock\\alarmday.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\Clock\\alarmday.c -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\alarmday.o

$(OBJDIR_APP_DEBUG)\\__\\Clock\\main.o: ..\\Clock\\main.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\Clock\\main.c -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\main.o

$(OBJDIR_APP_DEBUG)\\__\\Clock\\menu.o: ..\\Clock\\menu.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\Clock\\menu.c -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\menu.o

$(OBJDIR_APP_DEBUG)\\__\\Clock\\mouse.o: ..\\Clock\\mouse.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\Clock\\mouse.c -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\mouse.o

$(OBJDIR_APP_DEBUG)\\__\\Clock\\pageabout.o: ..\\Clock\\pageabout.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\Clock\\pageabout.c -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\pageabout.o

$(OBJDIR_APP_DEBUG)\\__\\Clock\\pagealarm.o: ..\\Clock\\pagealarm.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\Clock\\pagealarm.c -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\pagealarm.o

$(OBJDIR_APP_DEBUG)\\__\\Clock\\pagecolor.o: ..\\Clock\\pagecolor.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\Clock\\pagecolor.c -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\pagecolor.o

$(OBJDIR_APP_DEBUG)\\__\\Clock\\pageformat.o: ..\\Clock\\pageformat.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\Clock\\pageformat.c -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\pageformat.o

$(OBJDIR_APP_DEBUG)\\__\\Clock\\propsheet.o: ..\\Clock\\propsheet.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\Clock\\propsheet.c -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\propsheet.o

$(OBJDIR_APP_DEBUG)\\__\\Clock\\settings.o: ..\\Clock\\settings.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\Clock\\settings.c -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\settings.o

$(OBJDIR_APP_DEBUG)\\__\\Clock\\soundselect.o: ..\\Clock\\soundselect.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\Clock\\soundselect.c -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\soundselect.o

$(OBJDIR_APP_DEBUG)\\__\\Clock\\tClock.o: ..\\Clock\\tClock.rc
	$(WINDRES1) -i ..\\Clock\\tClock.rc -J rc -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\tClock.o -O coff $(INC_APP_DEBUG)

$(OBJDIR_APP_DEBUG)\\__\\Clock\\timer.o: ..\\Clock\\timer.c
	$(CC1) $(CFLAGS_APP_DEBUG) $(INC_APP_DEBUG) -c ..\\Clock\\timer.c -o $(OBJDIR_APP_DEBUG)\\__\\Clock\\timer.o

clean_app_debug: 
	cmd /c del /f $(OBJ_APP_DEBUG) $(OUT_APP_DEBUG)
	cmd /c rd $(OBJDIR_APP_DEBUG)\\__\\common
	cmd /c rd $(OBJDIR_APP_DEBUG)\\__\\Clock

before_dll_debug: 
	../common/AutoVersion --git . ../common/version.h
	cmd /c if not exist ..\\..\\Debug\\misc md ..\\..\\Debug\\misc
	cmd /c if not exist $(OBJDIR_DLL_DEBUG)\\__\\DLL md $(OBJDIR_DLL_DEBUG)\\__\\DLL
	cmd /c if not exist $(OBJDIR_DLL_DEBUG)\\__\\common md $(OBJDIR_DLL_DEBUG)\\__\\common

after_dll_debug: 
	objcopy --only-keep-debug ../../Debug/misc/T-Clock.dll ../../Debug/misc/T-Clock.dbg
	objcopy --strip-debug --strip-unneeded --add-gnu-debuglink=../../Debug/misc/T-Clock.dbg ../../Debug/misc/T-Clock.dll

dll_debug: before_dll_debug out_dll_debug after_dll_debug

out_dll_debug: before_dll_debug $(OBJ_DLL_DEBUG) $(DEP_DLL_DEBUG)
	$(LD1) -shared $(LIBDIR_DLL_DEBUG) $(OBJ_DLL_DEBUG)  -o $(OUT_DLL_DEBUG) $(LDFLAGS_DLL_DEBUG) $(LIB_DLL_DEBUG)

$(OBJDIR_DLL_DEBUG)\\__\\DLL\\Tclock.o: ..\\DLL\\Tclock.c
	$(CC1) $(CFLAGS_DLL_DEBUG) $(INC_DLL_DEBUG) -c ..\\DLL\\Tclock.c -o $(OBJDIR_DLL_DEBUG)\\__\\DLL\\Tclock.o

$(OBJDIR_DLL_DEBUG)\\__\\DLL\\clock_api.o: ..\\DLL\\clock_api.c
	$(CC1) $(CFLAGS_DLL_DEBUG) $(INC_DLL_DEBUG) -c ..\\DLL\\clock_api.c -o $(OBJDIR_DLL_DEBUG)\\__\\DLL\\clock_api.o

$(OBJDIR_DLL_DEBUG)\\__\\DLL\\clock_color.o: ..\\DLL\\clock_color.c
	$(CC1) $(CFLAGS_DLL_DEBUG) $(INC_DLL_DEBUG) -c ..\\DLL\\clock_color.c -o $(OBJDIR_DLL_DEBUG)\\__\\DLL\\clock_color.o

$(OBJDIR_DLL_DEBUG)\\__\\DLL\\clock_utils.o: ..\\DLL\\clock_utils.c
	$(CC1) $(CFLAGS_DLL_DEBUG) $(INC_DLL_DEBUG) -c ..\\DLL\\clock_utils.c -o $(OBJDIR_DLL_DEBUG)\\__\\DLL\\clock_utils.o

$(OBJDIR_DLL_DEBUG)\\__\\DLL\\font.o: ..\\DLL\\font.c
	$(CC1) $(CFLAGS_DLL_DEBUG) $(INC_DLL_DEBUG) -c ..\\DLL\\font.c -o $(OBJDIR_DLL_DEBUG)\\__\\DLL\\font.o

$(OBJDIR_DLL_DEBUG)\\__\\DLL\\format.o: ..\\DLL\\format.c
	$(CC1) $(CFLAGS_DLL_DEBUG) $(INC_DLL_DEBUG) -c ..\\DLL\\format.c -o $(OBJDIR_DLL_DEBUG)\\__\\DLL\\format.o

$(OBJDIR_DLL_DEBUG)\\__\\DLL\\main.o: ..\\DLL\\main.c
	$(CC1) $(CFLAGS_DLL_DEBUG) $(INC_DLL_DEBUG) -c ..\\DLL\\main.c -o $(OBJDIR_DLL_DEBUG)\\__\\DLL\\main.o

$(OBJDIR_DLL_DEBUG)\\__\\DLL\\version.o: ..\\DLL\\version.rc
	$(WINDRES1) -i ..\\DLL\\version.rc -J rc -o $(OBJDIR_DLL_DEBUG)\\__\\DLL\\version.o -O coff $(INC_DLL_DEBUG)

$(OBJDIR_DLL_DEBUG)\\__\\common\\newapi.o: ..\\common\\newapi.c
	$(CC1) $(CFLAGS_DLL_DEBUG) $(INC_DLL_DEBUG) -c ..\\common\\newapi.c -o $(OBJDIR_DLL_DEBUG)\\__\\common\\newapi.o

$(OBJDIR_DLL_DEBUG)\\__\\common\\utl.o: ..\\common\\utl.c
	$(CC1) $(CFLAGS_DLL_DEBUG) $(INC_DLL_DEBUG) -c ..\\common\\utl.c -o $(OBJDIR_DLL_DEBUG)\\__\\common\\utl.o

$(OBJDIR_DLL_DEBUG)\\__\\common\\win2k_compat.o: ..\\common\\win2k_compat.c
	$(CC1) $(CFLAGS_DLL_DEBUG) $(INC_DLL_DEBUG) -c ..\\common\\win2k_compat.c -o $(OBJDIR_DLL_DEBUG)\\__\\common\\win2k_compat.o

clean_dll_debug: 
	cmd /c del /f $(OBJ_DLL_DEBUG) $(OUT_DLL_DEBUG)
	cmd /c rd $(OBJDIR_DLL_DEBUG)\\__\\DLL
	cmd /c rd $(OBJDIR_DLL_DEBUG)\\__\\common

before_app_64: 
	../common/AutoVersion --git . ../common/version.h
	cmd /c if not exist ..\\..\\Release md ..\\..\\Release
	cmd /c if not exist $(OBJDIR_APP_64)\\__\\common md $(OBJDIR_APP_64)\\__\\common
	cmd /c if not exist $(OBJDIR_APP_64)\\__\\Clock md $(OBJDIR_APP_64)\\__\\Clock

after_app_64: 

app_64: before_app_64 out_app_64 after_app_64

out_app_64: before_app_64 $(OBJ_APP_64) $(DEP_APP_64)
	$(LD2) $(LIBDIR_APP_64) -o $(OUT_APP_64) $(OBJ_APP_64)  $(LDFLAGS_APP_64) -mwindows $(LIB_APP_64)

$(OBJDIR_APP_64)\\__\\common\\HaveSetTimePerms.o: ..\\common\\HaveSetTimePerms.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\common\\HaveSetTimePerms.c -o $(OBJDIR_APP_64)\\__\\common\\HaveSetTimePerms.o

$(OBJDIR_APP_64)\\__\\common\\clock.o: ..\\common\\clock.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\common\\clock.c -o $(OBJDIR_APP_64)\\__\\common\\clock.o

$(OBJDIR_APP_64)\\__\\common\\control_extensions.o: ..\\common\\control_extensions.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\common\\control_extensions.c -o $(OBJDIR_APP_64)\\__\\common\\control_extensions.o

$(OBJDIR_APP_64)\\__\\common\\newapi.o: ..\\common\\newapi.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\common\\newapi.c -o $(OBJDIR_APP_64)\\__\\common\\newapi.o

$(OBJDIR_APP_64)\\__\\common\\utl.o: ..\\common\\utl.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\common\\utl.c -o $(OBJDIR_APP_64)\\__\\common\\utl.o

$(OBJDIR_APP_64)\\__\\common\\win2k_compat.o: ..\\common\\win2k_compat.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\common\\win2k_compat.c -o $(OBJDIR_APP_64)\\__\\common\\win2k_compat.o

$(OBJDIR_APP_64)\\__\\Clock\\BounceWind.o: ..\\Clock\\BounceWind.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\Clock\\BounceWind.c -o $(OBJDIR_APP_64)\\__\\Clock\\BounceWind.o

$(OBJDIR_APP_64)\\__\\Clock\\ExitWindows.o: ..\\Clock\\ExitWindows.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\Clock\\ExitWindows.c -o $(OBJDIR_APP_64)\\__\\Clock\\ExitWindows.o

$(OBJDIR_APP_64)\\__\\Clock\\PageHotKey.o: ..\\Clock\\PageHotKey.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\Clock\\PageHotKey.c -o $(OBJDIR_APP_64)\\__\\Clock\\PageHotKey.o

$(OBJDIR_APP_64)\\__\\Clock\\PageMisc.o: ..\\Clock\\PageMisc.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\Clock\\PageMisc.c -o $(OBJDIR_APP_64)\\__\\Clock\\PageMisc.o

$(OBJDIR_APP_64)\\__\\Clock\\PageMouse.o: ..\\Clock\\PageMouse.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\Clock\\PageMouse.c -o $(OBJDIR_APP_64)\\__\\Clock\\PageMouse.o

$(OBJDIR_APP_64)\\__\\Clock\\PageQuicky.o: ..\\Clock\\PageQuicky.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\Clock\\PageQuicky.c -o $(OBJDIR_APP_64)\\__\\Clock\\PageQuicky.o

$(OBJDIR_APP_64)\\__\\Clock\\PageQuickyMenu.o: ..\\Clock\\PageQuickyMenu.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\Clock\\PageQuickyMenu.c -o $(OBJDIR_APP_64)\\__\\Clock\\PageQuickyMenu.o

$(OBJDIR_APP_64)\\__\\Clock\\SNTP.o: ..\\Clock\\SNTP.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\Clock\\SNTP.c -o $(OBJDIR_APP_64)\\__\\Clock\\SNTP.o

$(OBJDIR_APP_64)\\__\\Clock\\StopWatch.o: ..\\Clock\\StopWatch.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\Clock\\StopWatch.c -o $(OBJDIR_APP_64)\\__\\Clock\\StopWatch.o

$(OBJDIR_APP_64)\\__\\Clock\\alarm.o: ..\\Clock\\alarm.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\Clock\\alarm.c -o $(OBJDIR_APP_64)\\__\\Clock\\alarm.o

$(OBJDIR_APP_64)\\__\\Clock\\alarmday.o: ..\\Clock\\alarmday.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\Clock\\alarmday.c -o $(OBJDIR_APP_64)\\__\\Clock\\alarmday.o

$(OBJDIR_APP_64)\\__\\Clock\\main.o: ..\\Clock\\main.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\Clock\\main.c -o $(OBJDIR_APP_64)\\__\\Clock\\main.o

$(OBJDIR_APP_64)\\__\\Clock\\menu.o: ..\\Clock\\menu.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\Clock\\menu.c -o $(OBJDIR_APP_64)\\__\\Clock\\menu.o

$(OBJDIR_APP_64)\\__\\Clock\\mouse.o: ..\\Clock\\mouse.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\Clock\\mouse.c -o $(OBJDIR_APP_64)\\__\\Clock\\mouse.o

$(OBJDIR_APP_64)\\__\\Clock\\pageabout.o: ..\\Clock\\pageabout.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\Clock\\pageabout.c -o $(OBJDIR_APP_64)\\__\\Clock\\pageabout.o

$(OBJDIR_APP_64)\\__\\Clock\\pagealarm.o: ..\\Clock\\pagealarm.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\Clock\\pagealarm.c -o $(OBJDIR_APP_64)\\__\\Clock\\pagealarm.o

$(OBJDIR_APP_64)\\__\\Clock\\pagecolor.o: ..\\Clock\\pagecolor.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\Clock\\pagecolor.c -o $(OBJDIR_APP_64)\\__\\Clock\\pagecolor.o

$(OBJDIR_APP_64)\\__\\Clock\\pageformat.o: ..\\Clock\\pageformat.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\Clock\\pageformat.c -o $(OBJDIR_APP_64)\\__\\Clock\\pageformat.o

$(OBJDIR_APP_64)\\__\\Clock\\propsheet.o: ..\\Clock\\propsheet.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\Clock\\propsheet.c -o $(OBJDIR_APP_64)\\__\\Clock\\propsheet.o

$(OBJDIR_APP_64)\\__\\Clock\\settings.o: ..\\Clock\\settings.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\Clock\\settings.c -o $(OBJDIR_APP_64)\\__\\Clock\\settings.o

$(OBJDIR_APP_64)\\__\\Clock\\soundselect.o: ..\\Clock\\soundselect.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\Clock\\soundselect.c -o $(OBJDIR_APP_64)\\__\\Clock\\soundselect.o

$(OBJDIR_APP_64)\\__\\Clock\\tClock.o: ..\\Clock\\tClock.rc
	$(WINDRES2) -i ..\\Clock\\tClock.rc -J rc -o $(OBJDIR_APP_64)\\__\\Clock\\tClock.o -O coff $(INC_APP_64)

$(OBJDIR_APP_64)\\__\\Clock\\timer.o: ..\\Clock\\timer.c
	$(CC2) $(CFLAGS_APP_64) $(INC_APP_64) -c ..\\Clock\\timer.c -o $(OBJDIR_APP_64)\\__\\Clock\\timer.o

clean_app_64: 
	cmd /c del /f $(OBJ_APP_64) $(OUT_APP_64)
	cmd /c rd $(OBJDIR_APP_64)\\__\\common
	cmd /c rd $(OBJDIR_APP_64)\\__\\Clock

before_dll_64: 
	../common/AutoVersion --git . ../common/version.h
	cmd /c if not exist ..\\..\\Release\\misc md ..\\..\\Release\\misc
	cmd /c if not exist $(OBJDIR_DLL_64)\\__\\DLL md $(OBJDIR_DLL_64)\\__\\DLL
	cmd /c if not exist $(OBJDIR_DLL_64)\\__\\common md $(OBJDIR_DLL_64)\\__\\common

after_dll_64: 

dll_64: before_dll_64 out_dll_64 after_dll_64

out_dll_64: before_dll_64 $(OBJ_DLL_64) $(DEP_DLL_64)
	$(LD2) -shared $(LIBDIR_DLL_64) $(OBJ_DLL_64)  -o $(OUT_DLL_64) $(LDFLAGS_DLL_64) $(LIB_DLL_64)

$(OBJDIR_DLL_64)\\__\\DLL\\Tclock.o: ..\\DLL\\Tclock.c
	$(CC2) $(CFLAGS_DLL_64) $(INC_DLL_64) -c ..\\DLL\\Tclock.c -o $(OBJDIR_DLL_64)\\__\\DLL\\Tclock.o

$(OBJDIR_DLL_64)\\__\\DLL\\clock_api.o: ..\\DLL\\clock_api.c
	$(CC2) $(CFLAGS_DLL_64) $(INC_DLL_64) -c ..\\DLL\\clock_api.c -o $(OBJDIR_DLL_64)\\__\\DLL\\clock_api.o

$(OBJDIR_DLL_64)\\__\\DLL\\clock_color.o: ..\\DLL\\clock_color.c
	$(CC2) $(CFLAGS_DLL_64) $(INC_DLL_64) -c ..\\DLL\\clock_color.c -o $(OBJDIR_DLL_64)\\__\\DLL\\clock_color.o

$(OBJDIR_DLL_64)\\__\\DLL\\clock_utils.o: ..\\DLL\\clock_utils.c
	$(CC2) $(CFLAGS_DLL_64) $(INC_DLL_64) -c ..\\DLL\\clock_utils.c -o $(OBJDIR_DLL_64)\\__\\DLL\\clock_utils.o

$(OBJDIR_DLL_64)\\__\\DLL\\font.o: ..\\DLL\\font.c
	$(CC2) $(CFLAGS_DLL_64) $(INC_DLL_64) -c ..\\DLL\\font.c -o $(OBJDIR_DLL_64)\\__\\DLL\\font.o

$(OBJDIR_DLL_64)\\__\\DLL\\format.o: ..\\DLL\\format.c
	$(CC2) $(CFLAGS_DLL_64) $(INC_DLL_64) -c ..\\DLL\\format.c -o $(OBJDIR_DLL_64)\\__\\DLL\\format.o

$(OBJDIR_DLL_64)\\__\\DLL\\main.o: ..\\DLL\\main.c
	$(CC2) $(CFLAGS_DLL_64) $(INC_DLL_64) -c ..\\DLL\\main.c -o $(OBJDIR_DLL_64)\\__\\DLL\\main.o

$(OBJDIR_DLL_64)\\__\\DLL\\version.o: ..\\DLL\\version.rc
	$(WINDRES2) -i ..\\DLL\\version.rc -J rc -o $(OBJDIR_DLL_64)\\__\\DLL\\version.o -O coff $(INC_DLL_64)

$(OBJDIR_DLL_64)\\__\\common\\newapi.o: ..\\common\\newapi.c
	$(CC2) $(CFLAGS_DLL_64) $(INC_DLL_64) -c ..\\common\\newapi.c -o $(OBJDIR_DLL_64)\\__\\common\\newapi.o

$(OBJDIR_DLL_64)\\__\\common\\utl.o: ..\\common\\utl.c
	$(CC2) $(CFLAGS_DLL_64) $(INC_DLL_64) -c ..\\common\\utl.c -o $(OBJDIR_DLL_64)\\__\\common\\utl.o

$(OBJDIR_DLL_64)\\__\\common\\win2k_compat.o: ..\\common\\win2k_compat.c
	$(CC2) $(CFLAGS_DLL_64) $(INC_DLL_64) -c ..\\common\\win2k_compat.c -o $(OBJDIR_DLL_64)\\__\\common\\win2k_compat.o

clean_dll_64: 
	cmd /c del /f $(OBJ_DLL_64) $(OUT_DLL_64)
	cmd /c rd $(OBJDIR_DLL_64)\\__\\DLL
	cmd /c rd $(OBJDIR_DLL_64)\\__\\common

before_app_64_debug: 
	../common/AutoVersion --git . ../common/version.h
	cmd /c if not exist ..\\..\\Debug md ..\\..\\Debug
	cmd /c if not exist $(OBJDIR_APP_64_DEBUG)\\__\\common md $(OBJDIR_APP_64_DEBUG)\\__\\common
	cmd /c if not exist $(OBJDIR_APP_64_DEBUG)\\__\\Clock md $(OBJDIR_APP_64_DEBUG)\\__\\Clock

after_app_64_debug: 
	objcopy --only-keep-debug ../../Debug/Clock64.exe ../../Debug/Clock64.dbg
	objcopy --strip-debug --strip-unneeded --add-gnu-debuglink=../../Debug/Clock64.dbg ../../Debug/Clock64.exe

app_64_debug: before_app_64_debug out_app_64_debug after_app_64_debug

out_app_64_debug: before_app_64_debug $(OBJ_APP_64_DEBUG) $(DEP_APP_64_DEBUG)
	$(LD2) $(LIBDIR_APP_64_DEBUG) -o $(OUT_APP_64_DEBUG) $(OBJ_APP_64_DEBUG)  $(LDFLAGS_APP_64_DEBUG) -mwindows $(LIB_APP_64_DEBUG)

$(OBJDIR_APP_64_DEBUG)\\__\\common\\HaveSetTimePerms.o: ..\\common\\HaveSetTimePerms.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\common\\HaveSetTimePerms.c -o $(OBJDIR_APP_64_DEBUG)\\__\\common\\HaveSetTimePerms.o

$(OBJDIR_APP_64_DEBUG)\\__\\common\\clock.o: ..\\common\\clock.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\common\\clock.c -o $(OBJDIR_APP_64_DEBUG)\\__\\common\\clock.o

$(OBJDIR_APP_64_DEBUG)\\__\\common\\control_extensions.o: ..\\common\\control_extensions.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\common\\control_extensions.c -o $(OBJDIR_APP_64_DEBUG)\\__\\common\\control_extensions.o

$(OBJDIR_APP_64_DEBUG)\\__\\common\\newapi.o: ..\\common\\newapi.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\common\\newapi.c -o $(OBJDIR_APP_64_DEBUG)\\__\\common\\newapi.o

$(OBJDIR_APP_64_DEBUG)\\__\\common\\utl.o: ..\\common\\utl.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\common\\utl.c -o $(OBJDIR_APP_64_DEBUG)\\__\\common\\utl.o

$(OBJDIR_APP_64_DEBUG)\\__\\common\\win2k_compat.o: ..\\common\\win2k_compat.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\common\\win2k_compat.c -o $(OBJDIR_APP_64_DEBUG)\\__\\common\\win2k_compat.o

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\BounceWind.o: ..\\Clock\\BounceWind.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\Clock\\BounceWind.c -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\BounceWind.o

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\ExitWindows.o: ..\\Clock\\ExitWindows.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\Clock\\ExitWindows.c -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\ExitWindows.o

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\PageHotKey.o: ..\\Clock\\PageHotKey.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\Clock\\PageHotKey.c -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\PageHotKey.o

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\PageMisc.o: ..\\Clock\\PageMisc.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\Clock\\PageMisc.c -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\PageMisc.o

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\PageMouse.o: ..\\Clock\\PageMouse.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\Clock\\PageMouse.c -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\PageMouse.o

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\PageQuicky.o: ..\\Clock\\PageQuicky.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\Clock\\PageQuicky.c -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\PageQuicky.o

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\PageQuickyMenu.o: ..\\Clock\\PageQuickyMenu.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\Clock\\PageQuickyMenu.c -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\PageQuickyMenu.o

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\SNTP.o: ..\\Clock\\SNTP.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\Clock\\SNTP.c -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\SNTP.o

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\StopWatch.o: ..\\Clock\\StopWatch.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\Clock\\StopWatch.c -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\StopWatch.o

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\alarm.o: ..\\Clock\\alarm.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\Clock\\alarm.c -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\alarm.o

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\alarmday.o: ..\\Clock\\alarmday.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\Clock\\alarmday.c -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\alarmday.o

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\main.o: ..\\Clock\\main.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\Clock\\main.c -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\main.o

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\menu.o: ..\\Clock\\menu.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\Clock\\menu.c -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\menu.o

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\mouse.o: ..\\Clock\\mouse.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\Clock\\mouse.c -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\mouse.o

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\pageabout.o: ..\\Clock\\pageabout.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\Clock\\pageabout.c -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\pageabout.o

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\pagealarm.o: ..\\Clock\\pagealarm.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\Clock\\pagealarm.c -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\pagealarm.o

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\pagecolor.o: ..\\Clock\\pagecolor.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\Clock\\pagecolor.c -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\pagecolor.o

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\pageformat.o: ..\\Clock\\pageformat.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\Clock\\pageformat.c -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\pageformat.o

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\propsheet.o: ..\\Clock\\propsheet.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\Clock\\propsheet.c -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\propsheet.o

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\settings.o: ..\\Clock\\settings.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\Clock\\settings.c -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\settings.o

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\soundselect.o: ..\\Clock\\soundselect.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\Clock\\soundselect.c -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\soundselect.o

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\tClock.o: ..\\Clock\\tClock.rc
	$(WINDRES2) -i ..\\Clock\\tClock.rc -J rc -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\tClock.o -O coff $(INC_APP_64_DEBUG)

$(OBJDIR_APP_64_DEBUG)\\__\\Clock\\timer.o: ..\\Clock\\timer.c
	$(CC2) $(CFLAGS_APP_64_DEBUG) $(INC_APP_64_DEBUG) -c ..\\Clock\\timer.c -o $(OBJDIR_APP_64_DEBUG)\\__\\Clock\\timer.o

clean_app_64_debug: 
	cmd /c del /f $(OBJ_APP_64_DEBUG) $(OUT_APP_64_DEBUG)
	cmd /c rd $(OBJDIR_APP_64_DEBUG)\\__\\common
	cmd /c rd $(OBJDIR_APP_64_DEBUG)\\__\\Clock

before_dll_64_debug: 
	../common/AutoVersion --git . ../common/version.h
	cmd /c if not exist ..\\..\\Debug\\misc md ..\\..\\Debug\\misc
	cmd /c if not exist $(OBJDIR_DLL_64_DEBUG)\\__\\DLL md $(OBJDIR_DLL_64_DEBUG)\\__\\DLL
	cmd /c if not exist $(OBJDIR_DLL_64_DEBUG)\\__\\common md $(OBJDIR_DLL_64_DEBUG)\\__\\common

after_dll_64_debug: 
	objcopy --only-keep-debug ../../Debug/misc/T-Clock64.dll ../../Debug/misc/T-Clock64.dbg
	objcopy --strip-debug --strip-unneeded --add-gnu-debuglink=../../Debug/misc/T-Clock64.dbg ../../Debug/misc/T-Clock64.dll

dll_64_debug: before_dll_64_debug out_dll_64_debug after_dll_64_debug

out_dll_64_debug: before_dll_64_debug $(OBJ_DLL_64_DEBUG) $(DEP_DLL_64_DEBUG)
	$(LD2) -shared $(LIBDIR_DLL_64_DEBUG) $(OBJ_DLL_64_DEBUG)  -o $(OUT_DLL_64_DEBUG) $(LDFLAGS_DLL_64_DEBUG) $(LIB_DLL_64_DEBUG)

$(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\Tclock.o: ..\\DLL\\Tclock.c
	$(CC2) $(CFLAGS_DLL_64_DEBUG) $(INC_DLL_64_DEBUG) -c ..\\DLL\\Tclock.c -o $(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\Tclock.o

$(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\clock_api.o: ..\\DLL\\clock_api.c
	$(CC2) $(CFLAGS_DLL_64_DEBUG) $(INC_DLL_64_DEBUG) -c ..\\DLL\\clock_api.c -o $(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\clock_api.o

$(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\clock_color.o: ..\\DLL\\clock_color.c
	$(CC2) $(CFLAGS_DLL_64_DEBUG) $(INC_DLL_64_DEBUG) -c ..\\DLL\\clock_color.c -o $(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\clock_color.o

$(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\clock_utils.o: ..\\DLL\\clock_utils.c
	$(CC2) $(CFLAGS_DLL_64_DEBUG) $(INC_DLL_64_DEBUG) -c ..\\DLL\\clock_utils.c -o $(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\clock_utils.o

$(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\font.o: ..\\DLL\\font.c
	$(CC2) $(CFLAGS_DLL_64_DEBUG) $(INC_DLL_64_DEBUG) -c ..\\DLL\\font.c -o $(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\font.o

$(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\format.o: ..\\DLL\\format.c
	$(CC2) $(CFLAGS_DLL_64_DEBUG) $(INC_DLL_64_DEBUG) -c ..\\DLL\\format.c -o $(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\format.o

$(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\main.o: ..\\DLL\\main.c
	$(CC2) $(CFLAGS_DLL_64_DEBUG) $(INC_DLL_64_DEBUG) -c ..\\DLL\\main.c -o $(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\main.o

$(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\version.o: ..\\DLL\\version.rc
	$(WINDRES2) -i ..\\DLL\\version.rc -J rc -o $(OBJDIR_DLL_64_DEBUG)\\__\\DLL\\version.o -O coff $(INC_DLL_64_DEBUG)

$(OBJDIR_DLL_64_DEBUG)\\__\\common\\newapi.o: ..\\common\\newapi.c
	$(CC2) $(CFLAGS_DLL_64_DEBUG) $(INC_DLL_64_DEBUG) -c ..\\common\\newapi.c -o $(OBJDIR_DLL_64_DEBUG)\\__\\common\\newapi.o

$(OBJDIR_DLL_64_DEBUG)\\__\\common\\utl.o: ..\\common\\utl.c
	$(CC2) $(CFLAGS_DLL_64_DEBUG) $(INC_DLL_64_DEBUG) -c ..\\common\\utl.c -o $(OBJDIR_DLL_64_DEBUG)\\__\\common\\utl.o

$(OBJDIR_DLL_64_DEBUG)\\__\\common\\win2k_compat.o: ..\\common\\win2k_compat.c
	$(CC2) $(CFLAGS_DLL_64_DEBUG) $(INC_DLL_64_DEBUG) -c ..\\common\\win2k_compat.c -o $(OBJDIR_DLL_64_DEBUG)\\__\\common\\win2k_compat.o

clean_dll_64_debug: 
	cmd /c del /f $(OBJ_DLL_64_DEBUG) $(OUT_DLL_64_DEBUG)
	cmd /c rd $(OBJDIR_DLL_64_DEBUG)\\__\\DLL
	cmd /c rd $(OBJDIR_DLL_64_DEBUG)\\__\\common

virtual_debug: calendar_debug app_debug dll_debug app_64_debug dll_64_debug

.PHONY: before_autoversion after_autoversion clean_autoversion before_calendar after_calendar clean_calendar before_calendar_debug after_calendar_debug clean_calendar_debug before_app after_app clean_app before_dll after_dll clean_dll before_app_debug after_app_debug clean_app_debug before_dll_debug after_dll_debug clean_dll_debug before_app_64 after_app_64 clean_app_64 before_dll_64 after_dll_64 clean_dll_64 before_app_64_debug after_app_64_debug clean_app_64_debug before_dll_64_debug after_dll_64_debug clean_dll_64_debug

