#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = $(CCACHE) i686-w64-mingw32-gcc
CXX = $(CCACHE) i686-w64-mingw32-g++
AR = ar
LD = i686-w64-mingw32-g++
WINDRES = windres

INC = 
CFLAGS = -D_UNICODE -DUNICODE -fno-ident -Wall -m32 -Werror=declaration-after-statement -fvisibility=hidden -ffunction-sections -fmerge-all-constants -fno-asynchronous-unwind-tables -fno-exceptions -D_POSIX=1 -D_POSIX_C_SOURCE=200112L -D__STDC_FORMAT_MACROS -D__USE_MINGW_ANSI_STDIO=0 -D__MINGW_USE_VC2005_COMPAT -DWINVER=0x0501 -DPSAPI_VERSION=1 -DWIN2K_COMPAT
RESINC = 
LIBDIR = 
LIB = -ladvapi32 -lshell32 -luser32 -lgdi32 -lpsapi -lcomctl32 -lwinhttp
LDFLAGS = -static -m32 -Wl,--gc-sections

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O3 -DNDEBUG
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = ..\\.obj\\gcc
DEP_RELEASE = 
OUT_RELEASE = ..\\..\\Release\\misc\\Options.exe

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -Og -g -fno-omit-frame-pointer -D_DEBUG
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = ..\\.obj\\gcc\\dbg
DEP_DEBUG = 
OUT_DEBUG = ..\\..\\Debug\\misc\\Options.exe

OBJ_RELEASE = $(OBJDIR_RELEASE)\\__\\options\\update.o \
	$(OBJDIR_RELEASE)\\__\\options\\resource.o \
	$(OBJDIR_RELEASE)\\__\\options\\main.o \
	$(OBJDIR_RELEASE)\\__\\common\\win2k_compat.o \
	$(OBJDIR_RELEASE)\\__\\common\\utl.o \
	$(OBJDIR_RELEASE)\\__\\common\\newapi.o \
	$(OBJDIR_RELEASE)\\__\\common\\messagebox_custom.o \
	$(OBJDIR_RELEASE)\\__\\common\\getopt_tools.o \
	$(OBJDIR_RELEASE)\\__\\common\\clock.o

OBJ_DEBUG = $(OBJDIR_DEBUG)\\__\\options\\update.o \
	$(OBJDIR_DEBUG)\\__\\options\\resource.o \
	$(OBJDIR_DEBUG)\\__\\options\\main.o \
	$(OBJDIR_DEBUG)\\__\\common\\win2k_compat.o \
	$(OBJDIR_DEBUG)\\__\\common\\utl.o \
	$(OBJDIR_DEBUG)\\__\\common\\newapi.o \
	$(OBJDIR_DEBUG)\\__\\common\\messagebox_custom.o \
	$(OBJDIR_DEBUG)\\__\\common\\getopt_tools.o \
	$(OBJDIR_DEBUG)\\__\\common\\clock.o

all: before_build build_release build_debug after_build

clean: clean_release clean_debug

before_build: 
	../common/AutoVersion --git . ../common/version.h

after_build: 

before_release: 
	cmd /c if not exist ..\\..\\Release\\misc md ..\\..\\Release\\misc
	cmd /c if not exist $(OBJDIR_RELEASE)\\__\\options md $(OBJDIR_RELEASE)\\__\\options
	cmd /c if not exist $(OBJDIR_RELEASE)\\__\\common md $(OBJDIR_RELEASE)\\__\\common

after_release: 

build_release: before_release out_release after_release

release: before_build build_release after_build

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\__\\options\\update.o: ..\\options\\update.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ..\\options\\update.c -o $(OBJDIR_RELEASE)\\__\\options\\update.o

$(OBJDIR_RELEASE)\\__\\options\\resource.o: ..\\options\\resource.rc
	$(WINDRES) -i ..\\options\\resource.rc -J rc -o $(OBJDIR_RELEASE)\\__\\options\\resource.o -O coff $(INC_RELEASE)

$(OBJDIR_RELEASE)\\__\\options\\main.o: ..\\options\\main.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ..\\options\\main.c -o $(OBJDIR_RELEASE)\\__\\options\\main.o

$(OBJDIR_RELEASE)\\__\\common\\win2k_compat.o: ..\\common\\win2k_compat.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ..\\common\\win2k_compat.c -o $(OBJDIR_RELEASE)\\__\\common\\win2k_compat.o

$(OBJDIR_RELEASE)\\__\\common\\utl.o: ..\\common\\utl.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ..\\common\\utl.c -o $(OBJDIR_RELEASE)\\__\\common\\utl.o

$(OBJDIR_RELEASE)\\__\\common\\newapi.o: ..\\common\\newapi.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ..\\common\\newapi.c -o $(OBJDIR_RELEASE)\\__\\common\\newapi.o

$(OBJDIR_RELEASE)\\__\\common\\messagebox_custom.o: ..\\common\\messagebox_custom.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ..\\common\\messagebox_custom.c -o $(OBJDIR_RELEASE)\\__\\common\\messagebox_custom.o

$(OBJDIR_RELEASE)\\__\\common\\getopt_tools.o: ..\\common\\getopt_tools.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ..\\common\\getopt_tools.c -o $(OBJDIR_RELEASE)\\__\\common\\getopt_tools.o

$(OBJDIR_RELEASE)\\__\\common\\clock.o: ..\\common\\clock.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ..\\common\\clock.c -o $(OBJDIR_RELEASE)\\__\\common\\clock.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd $(OBJDIR_RELEASE)\\__\\options
	cmd /c rd $(OBJDIR_RELEASE)\\__\\common

before_debug: 
	cmd /c if not exist ..\\..\\Debug\\misc md ..\\..\\Debug\\misc
	cmd /c if not exist $(OBJDIR_DEBUG)\\__\\options md $(OBJDIR_DEBUG)\\__\\options
	cmd /c if not exist $(OBJDIR_DEBUG)\\__\\common md $(OBJDIR_DEBUG)\\__\\common

after_debug: 
	objcopy --only-keep-debug ../../Debug/misc/Options.exe ../../Debug/misc/Options.dbg
	objcopy --strip-debug --strip-unneeded --add-gnu-debuglink=../../Debug/misc/Options.dbg ../../Debug/misc/Options.exe

build_debug: before_debug out_debug after_debug

debug: before_build build_debug after_build

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)\\__\\options\\update.o: ..\\options\\update.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ..\\options\\update.c -o $(OBJDIR_DEBUG)\\__\\options\\update.o

$(OBJDIR_DEBUG)\\__\\options\\resource.o: ..\\options\\resource.rc
	$(WINDRES) -i ..\\options\\resource.rc -J rc -o $(OBJDIR_DEBUG)\\__\\options\\resource.o -O coff $(INC_DEBUG)

$(OBJDIR_DEBUG)\\__\\options\\main.o: ..\\options\\main.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ..\\options\\main.c -o $(OBJDIR_DEBUG)\\__\\options\\main.o

$(OBJDIR_DEBUG)\\__\\common\\win2k_compat.o: ..\\common\\win2k_compat.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ..\\common\\win2k_compat.c -o $(OBJDIR_DEBUG)\\__\\common\\win2k_compat.o

$(OBJDIR_DEBUG)\\__\\common\\utl.o: ..\\common\\utl.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ..\\common\\utl.c -o $(OBJDIR_DEBUG)\\__\\common\\utl.o

$(OBJDIR_DEBUG)\\__\\common\\newapi.o: ..\\common\\newapi.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ..\\common\\newapi.c -o $(OBJDIR_DEBUG)\\__\\common\\newapi.o

$(OBJDIR_DEBUG)\\__\\common\\messagebox_custom.o: ..\\common\\messagebox_custom.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ..\\common\\messagebox_custom.c -o $(OBJDIR_DEBUG)\\__\\common\\messagebox_custom.o

$(OBJDIR_DEBUG)\\__\\common\\getopt_tools.o: ..\\common\\getopt_tools.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ..\\common\\getopt_tools.c -o $(OBJDIR_DEBUG)\\__\\common\\getopt_tools.o

$(OBJDIR_DEBUG)\\__\\common\\clock.o: ..\\common\\clock.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c ..\\common\\clock.c -o $(OBJDIR_DEBUG)\\__\\common\\clock.o

clean_debug: 
	cmd /c del /f $(OBJ_DEBUG) $(OUT_DEBUG)
	cmd /c rd $(OBJDIR_DEBUG)\\__\\options
	cmd /c rd $(OBJDIR_DEBUG)\\__\\common

.PHONY: before_build after_build before_release after_release clean_release before_debug after_debug clean_debug

