#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -fno-ident -Wall -fvisibility=hidden -ffunction-sections -fmerge-all-constants -fno-asynchronous-unwind-tables -fno-exceptions -fwhole-program
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = -static -Wl,--gc-sections

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -Os -DNDEBUG
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = ../.obj/gcc
DEP_RELEASE = 
OUT_RELEASE = ../common/AutoVersion

OBJ_RELEASE = $(OBJDIR_RELEASE)/__/common/autoversion.o

all: release

clean: clean_release

before_release: 
	test -d ../common || mkdir -p ../common
	test -d $(OBJDIR_RELEASE)/__/common || mkdir -p $(OBJDIR_RELEASE)/__/common

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/__/common/autoversion.o: ../common/autoversion.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ../common/autoversion.cpp -o $(OBJDIR_RELEASE)/__/common/autoversion.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/__/common

.PHONY: before_release after_release clean_release

